/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window100 (void)
{
  GtkWidget *window100;
  GtkWidget *fixed100;
  GtkWidget *button101;
  GtkWidget *button103;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image100;
  GtkWidget *label101;
  GtkWidget *label100;
  GtkWidget *button100;

  window100 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window100), _("Gestion d'Hotel"));
  gtk_window_set_default_size (GTK_WINDOW (window100), 400, 300);

  fixed100 = gtk_fixed_new ();
  gtk_widget_show (fixed100);
  gtk_container_add (GTK_CONTAINER (window100), fixed100);

  button101 = gtk_button_new_with_mnemonic (_("Gestion de Reservation"));
  gtk_widget_show (button101);
  gtk_fixed_put (GTK_FIXED (fixed100), button101, 88, 160);
  gtk_widget_set_size_request (button101, 216, 56);

  button103 = gtk_button_new ();
  gtk_widget_show (button103);
  gtk_fixed_put (GTK_FIXED (fixed100), button103, 40, 256);
  gtk_widget_set_size_request (button103, 80, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button103), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image100 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image100);
  gtk_box_pack_start (GTK_BOX (hbox1), image100, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox1), label101, FALSE, FALSE, 0);

  label100 = gtk_label_new (_("Gestion d'Hotel"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed100), label100, 104, 16);
  gtk_widget_set_size_request (label100, 168, 56);

  button100 = gtk_button_new_with_mnemonic (_("Gestion d Hebergement "));
  gtk_widget_show (button100);
  gtk_fixed_put (GTK_FIXED (fixed100), button100, 88, 88);
  gtk_widget_set_size_request (button100, 216, 56);

  g_signal_connect ((gpointer) button100, "clicked",
                    G_CALLBACK (on_button100_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window100, window100, "window100");
  GLADE_HOOKUP_OBJECT (window100, fixed100, "fixed100");
  GLADE_HOOKUP_OBJECT (window100, button101, "button101");
  GLADE_HOOKUP_OBJECT (window100, button103, "button103");
  GLADE_HOOKUP_OBJECT (window100, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window100, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window100, image100, "image100");
  GLADE_HOOKUP_OBJECT (window100, label101, "label101");
  GLADE_HOOKUP_OBJECT (window100, label100, "label100");
  GLADE_HOOKUP_OBJECT (window100, button100, "button100");

  return window100;
}

GtkWidget*
create_window101 (void)
{
  GtkWidget *window101;
  GtkWidget *fixed101;
  GtkWidget *treeview100;
  GtkWidget *button104;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label400;
  GtkWidget *button107;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label700;
  GtkWidget *button105;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label500;
  GtkWidget *button106;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label600;
  GtkWidget *label102;

  window101 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window101), _("Gestion d'Hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window101), 800, 600);

  fixed101 = gtk_fixed_new ();
  gtk_widget_show (fixed101);
  gtk_container_add (GTK_CONTAINER (window101), fixed101);

  treeview100 = gtk_tree_view_new ();
  gtk_widget_show (treeview100);
  gtk_fixed_put (GTK_FIXED (fixed101), treeview100, 80, 72);
  gtk_widget_set_size_request (treeview100, 608, 312);

  button104 = gtk_button_new ();
  gtk_widget_show (button104);
  gtk_fixed_put (GTK_FIXED (fixed101), button104, 160, 432);
  gtk_widget_set_size_request (button104, 96, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button104), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label400 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label400);
  gtk_box_pack_start (GTK_BOX (hbox2), label400, FALSE, FALSE, 0);

  button107 = gtk_button_new ();
  gtk_widget_show (button107);
  gtk_fixed_put (GTK_FIXED (fixed101), button107, 56, 488);
  gtk_widget_set_size_request (button107, 96, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button107), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label700 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label700);
  gtk_box_pack_start (GTK_BOX (hbox5), label700, FALSE, FALSE, 0);

  button105 = gtk_button_new ();
  gtk_widget_show (button105);
  gtk_fixed_put (GTK_FIXED (fixed101), button105, 304, 432);
  gtk_widget_set_size_request (button105, 96, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button105), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label500 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label500);
  gtk_box_pack_start (GTK_BOX (hbox3), label500, FALSE, FALSE, 0);

  button106 = gtk_button_new ();
  gtk_widget_show (button106);
  gtk_fixed_put (GTK_FIXED (fixed101), button106, 440, 432);
  gtk_widget_set_size_request (button106, 112, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button106), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label600 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label600);
  gtk_box_pack_start (GTK_BOX (hbox4), label600, FALSE, FALSE, 0);

  label102 = gtk_label_new (_("Gestion d'Hebergement"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed101), label102, 264, 0);
  gtk_widget_set_size_request (label102, 200, 72);

  g_signal_connect ((gpointer) button105, "clicked",
                    G_CALLBACK (on_button105_clicked),
                    NULL);
  g_signal_connect ((gpointer) button106, "clicked",
                    G_CALLBACK (on_button106_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window101, window101, "window101");
  GLADE_HOOKUP_OBJECT (window101, fixed101, "fixed101");
  GLADE_HOOKUP_OBJECT (window101, treeview100, "treeview100");
  GLADE_HOOKUP_OBJECT (window101, button104, "button104");
  GLADE_HOOKUP_OBJECT (window101, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window101, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window101, image2, "image2");
  GLADE_HOOKUP_OBJECT (window101, label400, "label400");
  GLADE_HOOKUP_OBJECT (window101, button107, "button107");
  GLADE_HOOKUP_OBJECT (window101, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window101, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window101, image5, "image5");
  GLADE_HOOKUP_OBJECT (window101, label700, "label700");
  GLADE_HOOKUP_OBJECT (window101, button105, "button105");
  GLADE_HOOKUP_OBJECT (window101, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window101, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window101, image3, "image3");
  GLADE_HOOKUP_OBJECT (window101, label500, "label500");
  GLADE_HOOKUP_OBJECT (window101, button106, "button106");
  GLADE_HOOKUP_OBJECT (window101, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window101, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window101, image4, "image4");
  GLADE_HOOKUP_OBJECT (window101, label600, "label600");
  GLADE_HOOKUP_OBJECT (window101, label102, "label102");

  return window101;
}

GtkWidget*
create_window102 (void)
{
  GtkWidget *window102;
  GtkWidget *fixed102;
  GtkWidget *label107;
  GtkWidget *entry100;
  GtkWidget *entry101;
  GtkWidget *entry102;
  GtkWidget *label108;
  GtkWidget *label106;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *button108;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label14;
  GtkWidget *button109;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label15;
  GtkWidget *button110;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label17;
  GtkWidget *label105;

  window102 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window102), _("Modifier un Hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window102), 400, 600);

  fixed102 = gtk_fixed_new ();
  gtk_widget_show (fixed102);
  gtk_container_add (GTK_CONTAINER (window102), fixed102);

  label107 = gtk_label_new (_("Prix par nuite "));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed102), label107, 40, 224);
  gtk_widget_set_size_request (label107, 120, 40);

  entry100 = gtk_entry_new ();
  gtk_widget_show (entry100);
  gtk_fixed_put (GTK_FIXED (fixed102), entry100, 168, 176);
  gtk_widget_set_size_request (entry100, 152, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry100), 8226);

  entry101 = gtk_entry_new ();
  gtk_widget_show (entry101);
  gtk_fixed_put (GTK_FIXED (fixed102), entry101, 168, 232);
  gtk_widget_set_size_request (entry101, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry101), 8226);

  entry102 = gtk_entry_new ();
  gtk_widget_show (entry102);
  gtk_fixed_put (GTK_FIXED (fixed102), entry102, 168, 288);
  gtk_widget_set_size_request (entry102, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry102), 8226);

  label108 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed102), label108, 40, 280);
  gtk_widget_set_size_request (label108, 104, 40);

  label106 = gtk_label_new (_("Nom d'hotel"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed102), label106, 40, 168);
  gtk_widget_set_size_request (label106, 120, 48);

  label106 = gtk_label_new ("");
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed102), label106, 224, 480);
  gtk_widget_set_size_request (label106, 152, 56);

  label103 = gtk_label_new (_("Modifier un hebergement"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed102), label103, 112, 8);
  gtk_widget_set_size_request (label103, 184, 48);

  label104 = gtk_label_new (_("ID d'Hebergement"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed102), label104, 32, 64);
  gtk_widget_set_size_request (label104, 168, 56);

  button108 = gtk_button_new ();
  gtk_widget_show (button108);
  gtk_fixed_put (GTK_FIXED (fixed102), button108, 216, 400);
  gtk_widget_set_size_request (button108, 96, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button108), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox6), label14, FALSE, FALSE, 0);

  button109 = gtk_button_new ();
  gtk_widget_show (button109);
  gtk_fixed_put (GTK_FIXED (fixed102), button109, 96, 400);
  gtk_widget_set_size_request (button109, 88, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button109), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox7), label15, FALSE, FALSE, 0);

  button110 = gtk_button_new ();
  gtk_widget_show (button110);
  gtk_fixed_put (GTK_FIXED (fixed102), button110, 56, 496);
  gtk_widget_set_size_request (button110, 74, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button110), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);

  label105 = gtk_label_new ("");
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed102), label105, 192, 64);
  gtk_widget_set_size_request (label105, 128, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window102, window102, "window102");
  GLADE_HOOKUP_OBJECT (window102, fixed102, "fixed102");
  GLADE_HOOKUP_OBJECT (window102, label107, "label107");
  GLADE_HOOKUP_OBJECT (window102, entry100, "entry100");
  GLADE_HOOKUP_OBJECT (window102, entry101, "entry101");
  GLADE_HOOKUP_OBJECT (window102, entry102, "entry102");
  GLADE_HOOKUP_OBJECT (window102, label108, "label108");
  GLADE_HOOKUP_OBJECT (window102, label106, "label106");
  GLADE_HOOKUP_OBJECT (window102, label106, "label106");
  GLADE_HOOKUP_OBJECT (window102, label103, "label103");
  GLADE_HOOKUP_OBJECT (window102, label104, "label104");
  GLADE_HOOKUP_OBJECT (window102, button108, "button108");
  GLADE_HOOKUP_OBJECT (window102, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window102, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window102, image6, "image6");
  GLADE_HOOKUP_OBJECT (window102, label14, "label14");
  GLADE_HOOKUP_OBJECT (window102, button109, "button109");
  GLADE_HOOKUP_OBJECT (window102, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window102, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window102, image7, "image7");
  GLADE_HOOKUP_OBJECT (window102, label15, "label15");
  GLADE_HOOKUP_OBJECT (window102, button110, "button110");
  GLADE_HOOKUP_OBJECT (window102, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window102, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window102, image8, "image8");
  GLADE_HOOKUP_OBJECT (window102, label17, "label17");
  GLADE_HOOKUP_OBJECT (window102, label105, "label105");

  return window102;
}

GtkWidget*
create_window103 (void)
{
  GtkWidget *window103;
  GtkWidget *fixed103;
  GtkWidget *label107;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label106;
  GtkWidget *label108;
  GtkWidget *label105;
  GtkWidget *button111;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label24;
  GtkWidget *button112;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label25;
  GtkWidget *label109;
  GtkWidget *button113;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label26;

  window103 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window103), _("Ajouter un Hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window103), 400, 600);

  fixed103 = gtk_fixed_new ();
  gtk_widget_show (fixed103);
  gtk_container_add (GTK_CONTAINER (window103), fixed103);

  label107 = gtk_label_new (_("Nom d'hotel"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed103), label107, 48, 200);
  gtk_widget_set_size_request (label107, 136, 48);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed103), entry4, 168, 152);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed103), entry5, 168, 208);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed103), entry6, 168, 272);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed103), entry7, 168, 328);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label106 = gtk_label_new (_("ID d'Hebergement"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed103), label106, 16, 144);
  gtk_widget_set_size_request (label106, 168, 48);

  label108 = gtk_label_new (_("Prix par nuite"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed103), label108, 32, 264);
  gtk_widget_set_size_request (label108, 152, 40);

  label105 = gtk_label_new (_("Ajouter un hebergement"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed103), label105, 128, 40);
  gtk_widget_set_size_request (label105, 176, 48);

  button111 = gtk_button_new ();
  gtk_widget_show (button111);
  gtk_fixed_put (GTK_FIXED (fixed103), button111, 216, 456);
  gtk_widget_set_size_request (button111, 96, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button111), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox10), label24, FALSE, FALSE, 0);

  button112 = gtk_button_new ();
  gtk_widget_show (button112);
  gtk_fixed_put (GTK_FIXED (fixed103), button112, 72, 456);
  gtk_widget_set_size_request (button112, 104, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button112), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox11), label25, FALSE, FALSE, 0);

  label109 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed103), label109, 48, 312);
  gtk_widget_set_size_request (label109, 144, 64);

  button113 = gtk_button_new ();
  gtk_widget_show (button113);
  gtk_fixed_put (GTK_FIXED (fixed103), button113, 40, 528);
  gtk_widget_set_size_request (button113, 88, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button113), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox12), label26, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window103, window103, "window103");
  GLADE_HOOKUP_OBJECT (window103, fixed103, "fixed103");
  GLADE_HOOKUP_OBJECT (window103, label107, "label107");
  GLADE_HOOKUP_OBJECT (window103, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window103, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window103, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window103, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window103, label106, "label106");
  GLADE_HOOKUP_OBJECT (window103, label108, "label108");
  GLADE_HOOKUP_OBJECT (window103, label105, "label105");
  GLADE_HOOKUP_OBJECT (window103, button111, "button111");
  GLADE_HOOKUP_OBJECT (window103, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window103, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window103, image10, "image10");
  GLADE_HOOKUP_OBJECT (window103, label24, "label24");
  GLADE_HOOKUP_OBJECT (window103, button112, "button112");
  GLADE_HOOKUP_OBJECT (window103, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window103, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window103, image11, "image11");
  GLADE_HOOKUP_OBJECT (window103, label25, "label25");
  GLADE_HOOKUP_OBJECT (window103, label109, "label109");
  GLADE_HOOKUP_OBJECT (window103, button113, "button113");
  GLADE_HOOKUP_OBJECT (window103, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window103, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window103, image12, "image12");
  GLADE_HOOKUP_OBJECT (window103, label26, "label26");

  return window103;
}

GtkWidget*
create_window104 (void)
{
  GtkWidget *window104;
  GtkWidget *fixed104;
  GtkWidget *label110;
  GtkWidget *button115;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label29;
  GtkWidget *button116;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label28;
  GtkWidget *combobox100;

  window104 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window104), _("Selectionner l'Hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window104), 400, 200);

  fixed104 = gtk_fixed_new ();
  gtk_widget_show (fixed104);
  gtk_container_add (GTK_CONTAINER (window104), fixed104);

  label110 = gtk_label_new (_("Selectionner l'hotel a modifier"));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed104), label110, 96, 24);
  gtk_widget_set_size_request (label110, 224, 56);

  button115 = gtk_button_new ();
  gtk_widget_show (button115);
  gtk_fixed_put (GTK_FIXED (fixed104), button115, 224, 216);
  gtk_widget_set_size_request (button115, 120, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button115), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Selectionner"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox14), label29, FALSE, FALSE, 0);

  button116 = gtk_button_new ();
  gtk_widget_show (button116);
  gtk_fixed_put (GTK_FIXED (fixed104), button116, 40, 248);
  gtk_widget_set_size_request (button116, 96, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button116), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox13), label28, FALSE, FALSE, 0);

  combobox100 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox100);
  gtk_fixed_put (GTK_FIXED (fixed104), combobox100, 112, 120);
  gtk_widget_set_size_request (combobox100, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox100), _("E778998 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox100), _("E744546 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox100), _("E489945 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox100), _("E778222 "));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window104, window104, "window104");
  GLADE_HOOKUP_OBJECT (window104, fixed104, "fixed104");
  GLADE_HOOKUP_OBJECT (window104, label110, "label110");
  GLADE_HOOKUP_OBJECT (window104, button115, "button115");
  GLADE_HOOKUP_OBJECT (window104, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window104, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window104, image14, "image14");
  GLADE_HOOKUP_OBJECT (window104, label29, "label29");
  GLADE_HOOKUP_OBJECT (window104, button116, "button116");
  GLADE_HOOKUP_OBJECT (window104, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window104, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window104, image13, "image13");
  GLADE_HOOKUP_OBJECT (window104, label28, "label28");
  GLADE_HOOKUP_OBJECT (window104, combobox100, "combobox100");

  return window104;
}

GtkWidget*
create_window105 (void)
{
  GtkWidget *window105;
  GtkWidget *fixed6;
  GtkWidget *button118;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label31;
  GtkWidget *button119;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label33;
  GtkWidget *label111;
  GtkWidget *combobox101;
  GtkWidget *button117;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label32;

  window105 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window105), _("Supprimer l'hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window105), 400, 200);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window105), fixed6);

  button118 = gtk_button_new ();
  gtk_widget_show (button118);
  gtk_fixed_put (GTK_FIXED (fixed6), button118, 88, 200);
  gtk_widget_set_size_request (button118, 96, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button118), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox15), label31, FALSE, FALSE, 0);

  button119 = gtk_button_new ();
  gtk_widget_show (button119);
  gtk_fixed_put (GTK_FIXED (fixed6), button119, 32, 256);
  gtk_widget_set_size_request (button119, 88, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button119), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox17), label33, FALSE, FALSE, 0);

  label111 = gtk_label_new (_("Selectionner l'hotel a supprimer"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed6), label111, 40, 16);
  gtk_widget_set_size_request (label111, 312, 64);

  combobox101 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox101);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox101, 112, 112);
  gtk_widget_set_size_request (combobox101, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox101), _("E778998 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox101), _("E744546 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox101), _("E489945 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox101), _("E778222 "));

  button117 = gtk_button_new ();
  gtk_widget_show (button117);
  gtk_fixed_put (GTK_FIXED (fixed6), button117, 232, 200);
  gtk_widget_set_size_request (button117, 112, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button117), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox16), label32, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button117, "clicked",
                    G_CALLBACK (on_button117_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window105, window105, "window105");
  GLADE_HOOKUP_OBJECT (window105, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window105, button118, "button118");
  GLADE_HOOKUP_OBJECT (window105, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window105, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window105, image15, "image15");
  GLADE_HOOKUP_OBJECT (window105, label31, "label31");
  GLADE_HOOKUP_OBJECT (window105, button119, "button119");
  GLADE_HOOKUP_OBJECT (window105, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window105, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window105, image17, "image17");
  GLADE_HOOKUP_OBJECT (window105, label33, "label33");
  GLADE_HOOKUP_OBJECT (window105, label111, "label111");
  GLADE_HOOKUP_OBJECT (window105, combobox101, "combobox101");
  GLADE_HOOKUP_OBJECT (window105, button117, "button117");
  GLADE_HOOKUP_OBJECT (window105, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window105, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window105, image16, "image16");
  GLADE_HOOKUP_OBJECT (window105, label32, "label32");

  return window105;
}

