/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window100 (void);
GtkWidget* create_window101 (void);
GtkWidget* create_window102 (void);
GtkWidget* create_window103 (void);
GtkWidget* create_window104 (void);
GtkWidget* create_window105 (void);
