/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestionexcursionce (void);
GtkWidget* create_supprimerexcursione (void);
GtkWidget* create_ajouterexcursione (void);
GtkWidget* create_modifierexcursione (void);
GtkWidget* create_reserverexcursione (void);
GtkWidget* create_reserverexcursionc (void);
GtkWidget* create_afficherexcursionc (void);
GtkWidget* create_afficherexcursionclientnonconnecte (void);
GtkWidget* create_confirmersupprimerexcursione (void);
GtkWidget* create_confirmerajouterexcursion (void);
GtkWidget* create_confirmermodifierexcursion (void);
GtkWidget* create_espaceexcursion (void);
GtkWidget* create_excursionamodifierw (void);
