/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_reclamationclient (void);
GtkWidget* create_msgconfimationrec (void);
GtkWidget* create_reponsereclamation (void);
GtkWidget* create_tabrecclient (void);
GtkWidget* create_tabrecadmin (void);
GtkWidget* create_suppressionderecadmin (void);
GtkWidget* create_suppressionderecclient (void);
GtkWidget* create_messageconfirmationsupp (void);
GtkWidget* create_modifierreclamationclient (void);
GtkWidget* create_selctionnerafficherreclamation (void);
GtkWidget* create_selectmodfierreclamation (void);
GtkWidget* create_test_rec (void);
GtkWidget* create_msgreponserec (void);
GtkWidget* create_confirmationsupprimerrec (void);
GtkWidget* create_confirmationarchiverrec (void);
