/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_menufacdevis (void);
GtkWidget* create_Window_codeCDH (void);
GtkWidget* create_window_codeCDE (void);
GtkWidget* create_window_codeCDV (void);
GtkWidget* create_WAnnuler_CDH (void);
GtkWidget* create_WAnnuler_CDE (void);
GtkWidget* create_WAnnuler_CDV (void);
GtkWidget* create_WContinuer_CDH (void);
GtkWidget* create_WContinuer_CDE (void);
GtkWidget* create_WContinuer_CDV (void);
GtkWidget* create_WModifier_CDH (void);
GtkWidget* create_WModifier_CDE (void);
GtkWidget* create_WModifier_CDV (void);
GtkWidget* create_Reservation_annulerH (void);
GtkWidget* create_Reduction_validerH (void);
GtkWidget* create_Reservation_annulerE (void);
GtkWidget* create_Reservation_annulerV (void);
GtkWidget* create_Reduction_validerE (void);
GtkWidget* create_Reduction_validerV (void);
GtkWidget* create_Window (void);
GtkWidget* create_Facpayee (void);
GtkWidget* create_bienvenueespece (void);
GtkWidget* create_mode_payement (void);
GtkWidget* create_Payement (void);
GtkWidget* create_mode_payement_E (void);
GtkWidget* create_mode_payement_V (void);
GtkWidget* create_PayementE (void);
GtkWidget* create_PayementV (void);
