/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_menufacdevis (void)
{
  GtkWidget *menufacdevis;
  GtkWidget *notebook1;
  GtkWidget *notebook2;
  GtkWidget *notebook3;
  GtkWidget *fixed1;
  GtkWidget *treeviewADH;
  GtkWidget *Modifier_ADH;
  GtkWidget *label3;
  GtkWidget *fixed2;
  GtkWidget *treeviewADE;
  GtkWidget *Modifier_ADE;
  GtkWidget *label6;
  GtkWidget *fixed3;
  GtkWidget *treeviewADV;
  GtkWidget *Modifier_ADV;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *notebook4;
  GtkWidget *fixed4;
  GtkWidget *treeviewAFH;
  GtkWidget *label11;
  GtkWidget *fixed5;
  GtkWidget *treeviewAFE;
  GtkWidget *label12;
  GtkWidget *fixed6;
  GtkWidget *treeviewAFV;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *notebook5;
  GtkWidget *notebook6;
  GtkWidget *Fixed;
  GtkWidget *treeviewCDH;
  GtkWidget *entrycodeCDH;
  GtkWidget *label16;
  GtkWidget *ValiderCDH;
  GtkWidget *ContinuerCDH;
  GtkWidget *AnnulerCDH;
  GtkWidget *label18;
  GtkWidget *fixed8;
  GtkWidget *treeviewCDE;
  GtkWidget *entrycodeCDE;
  GtkWidget *label20;
  GtkWidget *AnnulerCDE;
  GtkWidget *ContinuerCDE;
  GtkWidget *ValiderCDE;
  GtkWidget *label21;
  GtkWidget *fixed9;
  GtkWidget *treeviewCDV;
  GtkWidget *entrycodeCDV;
  GtkWidget *label22;
  GtkWidget *ValiderCDV;
  GtkWidget *ContinuerCDV;
  GtkWidget *AnnulerCDV;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *notebook7;
  GtkWidget *fixed10;
  GtkWidget *treeviewCFH;
  GtkWidget *label27;
  GtkWidget *fixed11;
  GtkWidget *treeviewCFE;
  GtkWidget *label29;
  GtkWidget *fixed12;
  GtkWidget *treeviewCFV;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;

  menufacdevis = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menufacdevis), _("Menu"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (menufacdevis), notebook1);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook2);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_container_add (GTK_CONTAINER (notebook2), notebook3);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed1);

  treeviewADH = gtk_tree_view_new ();
  gtk_widget_show (treeviewADH);
  gtk_fixed_put (GTK_FIXED (fixed1), treeviewADH, 8, 24);
  gtk_widget_set_size_request (treeviewADH, 1100, 250);

  Modifier_ADH = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (Modifier_ADH);
  gtk_fixed_put (GTK_FIXED (fixed1), Modifier_ADH, 1008, 296);
  gtk_widget_set_size_request (Modifier_ADH, 82, 32);

  label3 = gtk_label_new (_("     Hebergement     "));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label3);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed2);

  treeviewADE = gtk_tree_view_new ();
  gtk_widget_show (treeviewADE);
  gtk_fixed_put (GTK_FIXED (fixed2), treeviewADE, 8, 16);
  gtk_widget_set_size_request (treeviewADE, 1000, 250);

  Modifier_ADE = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (Modifier_ADE);
  gtk_fixed_put (GTK_FIXED (fixed2), Modifier_ADE, 936, 280);
  gtk_widget_set_size_request (Modifier_ADE, 70, 29);

  label6 = gtk_label_new (_("     Excursion     "));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label6);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed3);

  treeviewADV = gtk_tree_view_new ();
  gtk_widget_show (treeviewADV);
  gtk_fixed_put (GTK_FIXED (fixed3), treeviewADV, 8, 16);
  gtk_widget_set_size_request (treeviewADV, 1000, 250);

  Modifier_ADV = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (Modifier_ADV);
  gtk_fixed_put (GTK_FIXED (fixed3), Modifier_ADV, 936, 288);
  gtk_widget_set_size_request (Modifier_ADV, 70, 29);

  label9 = gtk_label_new (_("     Vol     "));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label9);

  label10 = gtk_label_new (_("     Devis     "));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label10);

  notebook4 = gtk_notebook_new ();
  gtk_widget_show (notebook4);
  gtk_container_add (GTK_CONTAINER (notebook2), notebook4);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed4);

  treeviewAFH = gtk_tree_view_new ();
  gtk_widget_show (treeviewAFH);
  gtk_fixed_put (GTK_FIXED (fixed4), treeviewAFH, 8, 16);
  gtk_widget_set_size_request (treeviewAFH, 1100, 250);

  label11 = gtk_label_new (_("     Hebergement     "));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), label11);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed5);

  treeviewAFE = gtk_tree_view_new ();
  gtk_widget_show (treeviewAFE);
  gtk_fixed_put (GTK_FIXED (fixed5), treeviewAFE, 16, 16);
  gtk_widget_set_size_request (treeviewAFE, 1000, 250);

  label12 = gtk_label_new (_("     Excursion     "));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), label12);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed6);

  treeviewAFV = gtk_tree_view_new ();
  gtk_widget_show (treeviewAFV);
  gtk_fixed_put (GTK_FIXED (fixed6), treeviewAFV, 16, 24);
  gtk_widget_set_size_request (treeviewAFV, 1000, 250);

  label13 = gtk_label_new (_("     Vol     "));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 2), label13);

  label14 = gtk_label_new (_("     Facture     "));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label14);

  label15 = gtk_label_new (_("     Administrateur     "));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label15);

  notebook5 = gtk_notebook_new ();
  gtk_widget_show (notebook5);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook5);

  notebook6 = gtk_notebook_new ();
  gtk_widget_show (notebook6);
  gtk_container_add (GTK_CONTAINER (notebook5), notebook6);

  Fixed = gtk_fixed_new ();
  gtk_widget_show (Fixed);
  gtk_container_add (GTK_CONTAINER (notebook6), Fixed);

  treeviewCDH = gtk_tree_view_new ();
  gtk_widget_show (treeviewCDH);
  gtk_fixed_put (GTK_FIXED (Fixed), treeviewCDH, 8, 32);
  gtk_widget_set_size_request (treeviewCDH, 1100, 250);

  entrycodeCDH = gtk_entry_new ();
  gtk_widget_show (entrycodeCDH);
  gtk_fixed_put (GTK_FIXED (Fixed), entrycodeCDH, 840, 320);
  gtk_widget_set_size_request (entrycodeCDH, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycodeCDH), 8226);

  label16 = gtk_label_new (_("Code promos"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (Fixed), label16, 728, 325);
  gtk_widget_set_size_request (label16, 96, 16);

  ValiderCDH = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (ValiderCDH);
  gtk_fixed_put (GTK_FIXED (Fixed), ValiderCDH, 920, 360);
  gtk_widget_set_size_request (ValiderCDH, 66, 29);

  ContinuerCDH = gtk_button_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (ContinuerCDH);
  gtk_fixed_put (GTK_FIXED (Fixed), ContinuerCDH, 752, 456);
  gtk_widget_set_size_request (ContinuerCDH, 85, 29);

  AnnulerCDH = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (AnnulerCDH);
  gtk_fixed_put (GTK_FIXED (Fixed), AnnulerCDH, 200, 456);
  gtk_widget_set_size_request (AnnulerCDH, 85, 29);

  label18 = gtk_label_new (_("     Hebergement     "));
  gtk_widget_show (label18);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 0), label18);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed8);

  treeviewCDE = gtk_tree_view_new ();
  gtk_widget_show (treeviewCDE);
  gtk_fixed_put (GTK_FIXED (fixed8), treeviewCDE, 8, 32);
  gtk_widget_set_size_request (treeviewCDE, 1000, 250);

  entrycodeCDE = gtk_entry_new ();
  gtk_widget_show (entrycodeCDE);
  gtk_fixed_put (GTK_FIXED (fixed8), entrycodeCDE, 840, 320);
  gtk_widget_set_size_request (entrycodeCDE, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycodeCDE), 8226);

  label20 = gtk_label_new (_("Code promos"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed8), label20, 728, 325);
  gtk_widget_set_size_request (label20, 104, 16);

  AnnulerCDE = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (AnnulerCDE);
  gtk_fixed_put (GTK_FIXED (fixed8), AnnulerCDE, 200, 464);
  gtk_widget_set_size_request (AnnulerCDE, 85, 29);

  ContinuerCDE = gtk_button_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (ContinuerCDE);
  gtk_fixed_put (GTK_FIXED (fixed8), ContinuerCDE, 752, 456);
  gtk_widget_set_size_request (ContinuerCDE, 85, 29);

  ValiderCDE = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (ValiderCDE);
  gtk_fixed_put (GTK_FIXED (fixed8), ValiderCDE, 920, 360);
  gtk_widget_set_size_request (ValiderCDE, 74, 29);

  label21 = gtk_label_new (_("     Excursion     "));
  gtk_widget_show (label21);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 1), label21);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed9);

  treeviewCDV = gtk_tree_view_new ();
  gtk_widget_show (treeviewCDV);
  gtk_fixed_put (GTK_FIXED (fixed9), treeviewCDV, 0, 32);
  gtk_widget_set_size_request (treeviewCDV, 1000, 250);

  entrycodeCDV = gtk_entry_new ();
  gtk_widget_show (entrycodeCDV);
  gtk_fixed_put (GTK_FIXED (fixed9), entrycodeCDV, 816, 304);
  gtk_widget_set_size_request (entrycodeCDV, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycodeCDV), 8226);

  label22 = gtk_label_new (_("Code promos"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed9), label22, 680, 312);
  gtk_widget_set_size_request (label22, 120, 16);

  ValiderCDV = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (ValiderCDV);
  gtk_fixed_put (GTK_FIXED (fixed9), ValiderCDV, 888, 352);
  gtk_widget_set_size_request (ValiderCDV, 74, 29);

  ContinuerCDV = gtk_button_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (ContinuerCDV);
  gtk_fixed_put (GTK_FIXED (fixed9), ContinuerCDV, 760, 448);
  gtk_widget_set_size_request (ContinuerCDV, 85, 29);

  AnnulerCDV = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (AnnulerCDV);
  gtk_fixed_put (GTK_FIXED (fixed9), AnnulerCDV, 192, 456);
  gtk_widget_set_size_request (AnnulerCDV, 85, 29);

  label24 = gtk_label_new (_("     Vol     "));
  gtk_widget_show (label24);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 2), label24);

  label25 = gtk_label_new (_("     Devis     "));
  gtk_widget_show (label25);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 0), label25);

  notebook7 = gtk_notebook_new ();
  gtk_widget_show (notebook7);
  gtk_container_add (GTK_CONTAINER (notebook5), notebook7);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook7), fixed10);

  treeviewCFH = gtk_tree_view_new ();
  gtk_widget_show (treeviewCFH);
  gtk_fixed_put (GTK_FIXED (fixed10), treeviewCFH, 8, 24);
  gtk_widget_set_size_request (treeviewCFH, 1100, 250);

  label27 = gtk_label_new (_("     Hebergement     "));
  gtk_widget_show (label27);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 0), label27);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook7), fixed11);

  treeviewCFE = gtk_tree_view_new ();
  gtk_widget_show (treeviewCFE);
  gtk_fixed_put (GTK_FIXED (fixed11), treeviewCFE, 0, 24);
  gtk_widget_set_size_request (treeviewCFE, 1000, 250);

  label29 = gtk_label_new (_("     Excursion     "));
  gtk_widget_show (label29);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 1), label29);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook7), fixed12);

  treeviewCFV = gtk_tree_view_new ();
  gtk_widget_show (treeviewCFV);
  gtk_fixed_put (GTK_FIXED (fixed12), treeviewCFV, 8, 16);
  gtk_widget_set_size_request (treeviewCFV, 1000, 250);

  label31 = gtk_label_new (_("     Vol     "));
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 2), label31);

  label32 = gtk_label_new (_("     Facture      "));
  gtk_widget_show (label32);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 1), label32);

  label33 = gtk_label_new (_("      Client     "));
  gtk_widget_show (label33);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label33);

  g_signal_connect ((gpointer) Modifier_ADH, "clicked",
                    G_CALLBACK (on_Modifier_ADH_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modifier_ADE, "clicked",
                    G_CALLBACK (on_Modifier_ADE_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modifier_ADV, "clicked",
                    G_CALLBACK (on_Modifier_ADV_clicked),
                    NULL);
  g_signal_connect ((gpointer) ValiderCDH, "clicked",
                    G_CALLBACK (on_ValiderCDH_clicked),
                    NULL);
  g_signal_connect ((gpointer) ContinuerCDH, "clicked",
                    G_CALLBACK (on_ContinuerCDH_clicked),
                    NULL);
  g_signal_connect ((gpointer) AnnulerCDH, "clicked",
                    G_CALLBACK (on_AnnulerCDH_clicked),
                    NULL);
  g_signal_connect ((gpointer) AnnulerCDE, "clicked",
                    G_CALLBACK (on_AnnulerCDE_clicked),
                    NULL);
  g_signal_connect ((gpointer) ContinuerCDE, "clicked",
                    G_CALLBACK (on_ContinuerCDE_clicked),
                    NULL);
  g_signal_connect ((gpointer) ValiderCDE, "clicked",
                    G_CALLBACK (on_ValiderCDE_clicked),
                    NULL);
  g_signal_connect ((gpointer) ValiderCDV, "clicked",
                    G_CALLBACK (on_ValiderCDV_clicked),
                    NULL);
  g_signal_connect ((gpointer) ContinuerCDV, "clicked",
                    G_CALLBACK (on_ContinuerCDV_clicked),
                    NULL);
  g_signal_connect ((gpointer) AnnulerCDV, "clicked",
                    G_CALLBACK (on_AnnulerCDV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menufacdevis, menufacdevis, "menufacdevis");
  GLADE_HOOKUP_OBJECT (menufacdevis, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (menufacdevis, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (menufacdevis, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewADH, "treeviewADH");
  GLADE_HOOKUP_OBJECT (menufacdevis, Modifier_ADH, "Modifier_ADH");
  GLADE_HOOKUP_OBJECT (menufacdevis, label3, "label3");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewADE, "treeviewADE");
  GLADE_HOOKUP_OBJECT (menufacdevis, Modifier_ADE, "Modifier_ADE");
  GLADE_HOOKUP_OBJECT (menufacdevis, label6, "label6");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewADV, "treeviewADV");
  GLADE_HOOKUP_OBJECT (menufacdevis, Modifier_ADV, "Modifier_ADV");
  GLADE_HOOKUP_OBJECT (menufacdevis, label9, "label9");
  GLADE_HOOKUP_OBJECT (menufacdevis, label10, "label10");
  GLADE_HOOKUP_OBJECT (menufacdevis, notebook4, "notebook4");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewAFH, "treeviewAFH");
  GLADE_HOOKUP_OBJECT (menufacdevis, label11, "label11");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewAFE, "treeviewAFE");
  GLADE_HOOKUP_OBJECT (menufacdevis, label12, "label12");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewAFV, "treeviewAFV");
  GLADE_HOOKUP_OBJECT (menufacdevis, label13, "label13");
  GLADE_HOOKUP_OBJECT (menufacdevis, label14, "label14");
  GLADE_HOOKUP_OBJECT (menufacdevis, label15, "label15");
  GLADE_HOOKUP_OBJECT (menufacdevis, notebook5, "notebook5");
  GLADE_HOOKUP_OBJECT (menufacdevis, notebook6, "notebook6");
  GLADE_HOOKUP_OBJECT (menufacdevis, Fixed, "Fixed");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewCDH, "treeviewCDH");
  GLADE_HOOKUP_OBJECT (menufacdevis, entrycodeCDH, "entrycodeCDH");
  GLADE_HOOKUP_OBJECT (menufacdevis, label16, "label16");
  GLADE_HOOKUP_OBJECT (menufacdevis, ValiderCDH, "ValiderCDH");
  GLADE_HOOKUP_OBJECT (menufacdevis, ContinuerCDH, "ContinuerCDH");
  GLADE_HOOKUP_OBJECT (menufacdevis, AnnulerCDH, "AnnulerCDH");
  GLADE_HOOKUP_OBJECT (menufacdevis, label18, "label18");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewCDE, "treeviewCDE");
  GLADE_HOOKUP_OBJECT (menufacdevis, entrycodeCDE, "entrycodeCDE");
  GLADE_HOOKUP_OBJECT (menufacdevis, label20, "label20");
  GLADE_HOOKUP_OBJECT (menufacdevis, AnnulerCDE, "AnnulerCDE");
  GLADE_HOOKUP_OBJECT (menufacdevis, ContinuerCDE, "ContinuerCDE");
  GLADE_HOOKUP_OBJECT (menufacdevis, ValiderCDE, "ValiderCDE");
  GLADE_HOOKUP_OBJECT (menufacdevis, label21, "label21");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewCDV, "treeviewCDV");
  GLADE_HOOKUP_OBJECT (menufacdevis, entrycodeCDV, "entrycodeCDV");
  GLADE_HOOKUP_OBJECT (menufacdevis, label22, "label22");
  GLADE_HOOKUP_OBJECT (menufacdevis, ValiderCDV, "ValiderCDV");
  GLADE_HOOKUP_OBJECT (menufacdevis, ContinuerCDV, "ContinuerCDV");
  GLADE_HOOKUP_OBJECT (menufacdevis, AnnulerCDV, "AnnulerCDV");
  GLADE_HOOKUP_OBJECT (menufacdevis, label24, "label24");
  GLADE_HOOKUP_OBJECT (menufacdevis, label25, "label25");
  GLADE_HOOKUP_OBJECT (menufacdevis, notebook7, "notebook7");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewCFH, "treeviewCFH");
  GLADE_HOOKUP_OBJECT (menufacdevis, label27, "label27");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewCFE, "treeviewCFE");
  GLADE_HOOKUP_OBJECT (menufacdevis, label29, "label29");
  GLADE_HOOKUP_OBJECT (menufacdevis, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (menufacdevis, treeviewCFV, "treeviewCFV");
  GLADE_HOOKUP_OBJECT (menufacdevis, label31, "label31");
  GLADE_HOOKUP_OBJECT (menufacdevis, label32, "label32");
  GLADE_HOOKUP_OBJECT (menufacdevis, label33, "label33");

  return menufacdevis;
}

GtkWidget*
create_Window_codeCDH (void)
{
  GtkWidget *Window_codeCDH;
  GtkWidget *fixed13;
  GtkWidget *introuvablecodeCDH;
  GtkWidget *OKcodeCDH;

  Window_codeCDH = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (Window_codeCDH), fixed13);

  introuvablecodeCDH = gtk_label_new ("");
  gtk_widget_show (introuvablecodeCDH);
  gtk_fixed_put (GTK_FIXED (fixed13), introuvablecodeCDH, 40, 48);
  gtk_widget_set_size_request (introuvablecodeCDH, 320, 96);

  OKcodeCDH = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKcodeCDH);
  gtk_fixed_put (GTK_FIXED (fixed13), OKcodeCDH, 160, 176);
  gtk_widget_set_size_request (OKcodeCDH, 66, 29);

  g_signal_connect ((gpointer) OKcodeCDH, "clicked",
                    G_CALLBACK (on_OKcodeCDH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Window_codeCDH, Window_codeCDH, "Window_codeCDH");
  GLADE_HOOKUP_OBJECT (Window_codeCDH, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Window_codeCDH, introuvablecodeCDH, "introuvablecodeCDH");
  GLADE_HOOKUP_OBJECT (Window_codeCDH, OKcodeCDH, "OKcodeCDH");

  return Window_codeCDH;
}

GtkWidget*
create_window_codeCDE (void)
{
  GtkWidget *window_codeCDE;
  GtkWidget *fixed14;
  GtkWidget *introuvablecodeCDE;
  GtkWidget *OKcodeCDE;

  window_codeCDE = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (window_codeCDE), fixed14);

  introuvablecodeCDE = gtk_label_new ("");
  gtk_widget_show (introuvablecodeCDE);
  gtk_fixed_put (GTK_FIXED (fixed14), introuvablecodeCDE, 64, 40);
  gtk_widget_set_size_request (introuvablecodeCDE, 264, 96);

  OKcodeCDE = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKcodeCDE);
  gtk_fixed_put (GTK_FIXED (fixed14), OKcodeCDE, 152, 168);
  gtk_widget_set_size_request (OKcodeCDE, 66, 29);

  g_signal_connect ((gpointer) OKcodeCDE, "clicked",
                    G_CALLBACK (on_OKcodeCDE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_codeCDE, window_codeCDE, "window_codeCDE");
  GLADE_HOOKUP_OBJECT (window_codeCDE, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (window_codeCDE, introuvablecodeCDE, "introuvablecodeCDE");
  GLADE_HOOKUP_OBJECT (window_codeCDE, OKcodeCDE, "OKcodeCDE");

  return window_codeCDE;
}

GtkWidget*
create_window_codeCDV (void)
{
  GtkWidget *window_codeCDV;
  GtkWidget *fixed15;
  GtkWidget *introuvablecodeCDV;
  GtkWidget *OKcodeCDV;

  window_codeCDV = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (window_codeCDV), fixed15);

  introuvablecodeCDV = gtk_label_new ("");
  gtk_widget_show (introuvablecodeCDV);
  gtk_fixed_put (GTK_FIXED (fixed15), introuvablecodeCDV, 40, 40);
  gtk_widget_set_size_request (introuvablecodeCDV, 344, 104);

  OKcodeCDV = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKcodeCDV);
  gtk_fixed_put (GTK_FIXED (fixed15), OKcodeCDV, 168, 160);
  gtk_widget_set_size_request (OKcodeCDV, 66, 29);

  g_signal_connect ((gpointer) OKcodeCDV, "clicked",
                    G_CALLBACK (on_OKcodeCDV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_codeCDV, window_codeCDV, "window_codeCDV");
  GLADE_HOOKUP_OBJECT (window_codeCDV, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (window_codeCDV, introuvablecodeCDV, "introuvablecodeCDV");
  GLADE_HOOKUP_OBJECT (window_codeCDV, OKcodeCDV, "OKcodeCDV");

  return window_codeCDV;
}

GtkWidget*
create_WAnnuler_CDH (void)
{
  GtkWidget *WAnnuler_CDH;
  GtkWidget *fixed16;
  GtkWidget *comboboxACDH;
  GtkWidget *R_AnnulerF_CDH;
  GtkWidget *AnnulerF_CDH;
  GtkWidget *label39;

  WAnnuler_CDH = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (WAnnuler_CDH), fixed16);

  comboboxACDH = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxACDH);
  gtk_fixed_put (GTK_FIXED (fixed16), comboboxACDH, 112, 64);
  gtk_widget_set_size_request (comboboxACDH, 155, 31);

  R_AnnulerF_CDH = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_AnnulerF_CDH);
  gtk_fixed_put (GTK_FIXED (fixed16), R_AnnulerF_CDH, 104, 112);
  gtk_widget_set_size_request (R_AnnulerF_CDH, 74, 29);

  AnnulerF_CDH = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (AnnulerF_CDH);
  gtk_fixed_put (GTK_FIXED (fixed16), AnnulerF_CDH, 200, 112);
  gtk_widget_set_size_request (AnnulerF_CDH, 66, 29);

  label39 = gtk_label_new (_("Selectionner l'identifiant du devis \303\240 annuler."));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed16), label39, 56, 8);
  gtk_widget_set_size_request (label39, 320, 56);

  g_signal_connect ((gpointer) R_AnnulerF_CDH, "clicked",
                    G_CALLBACK (on_R_AnnulerF_CDH_clicked),
                    NULL);
  g_signal_connect ((gpointer) AnnulerF_CDH, "clicked",
                    G_CALLBACK (on_AnnulerF_CDH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WAnnuler_CDH, WAnnuler_CDH, "WAnnuler_CDH");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDH, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDH, comboboxACDH, "comboboxACDH");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDH, R_AnnulerF_CDH, "R_AnnulerF_CDH");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDH, AnnulerF_CDH, "AnnulerF_CDH");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDH, label39, "label39");

  return WAnnuler_CDH;
}

GtkWidget*
create_WAnnuler_CDE (void)
{
  GtkWidget *WAnnuler_CDE;
  GtkWidget *fixed17;
  GtkWidget *comboboxACDE;
  GtkWidget *AnnulerF_CDE;
  GtkWidget *R_AnnulerF_CDE;
  GtkWidget *label38;

  WAnnuler_CDE = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (WAnnuler_CDE), fixed17);

  comboboxACDE = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxACDE);
  gtk_fixed_put (GTK_FIXED (fixed17), comboboxACDE, 96, 64);
  gtk_widget_set_size_request (comboboxACDE, 155, 31);

  AnnulerF_CDE = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (AnnulerF_CDE);
  gtk_fixed_put (GTK_FIXED (fixed17), AnnulerF_CDE, 184, 104);
  gtk_widget_set_size_request (AnnulerF_CDE, 66, 29);

  R_AnnulerF_CDE = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_AnnulerF_CDE);
  gtk_fixed_put (GTK_FIXED (fixed17), R_AnnulerF_CDE, 72, 104);
  gtk_widget_set_size_request (R_AnnulerF_CDE, 74, 29);

  label38 = gtk_label_new (_("Selectionner l'identifiant du devis \303\240 annuler."));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed17), label38, 40, 8);
  gtk_widget_set_size_request (label38, 320, 56);

  g_signal_connect ((gpointer) AnnulerF_CDE, "clicked",
                    G_CALLBACK (on_AnnulerF_CDE_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_AnnulerF_CDE, "clicked",
                    G_CALLBACK (on_R_AnnulerF_CDE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WAnnuler_CDE, WAnnuler_CDE, "WAnnuler_CDE");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDE, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDE, comboboxACDE, "comboboxACDE");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDE, AnnulerF_CDE, "AnnulerF_CDE");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDE, R_AnnulerF_CDE, "R_AnnulerF_CDE");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDE, label38, "label38");

  return WAnnuler_CDE;
}

GtkWidget*
create_WAnnuler_CDV (void)
{
  GtkWidget *WAnnuler_CDV;
  GtkWidget *fixed18;
  GtkWidget *comboboxACDV;
  GtkWidget *R_AnnulerF_CDV;
  GtkWidget *label37;
  GtkWidget *AnnulerF_CDV;

  WAnnuler_CDV = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (WAnnuler_CDV), fixed18);

  comboboxACDV = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxACDV);
  gtk_fixed_put (GTK_FIXED (fixed18), comboboxACDV, 112, 64);
  gtk_widget_set_size_request (comboboxACDV, 155, 31);

  R_AnnulerF_CDV = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_AnnulerF_CDV);
  gtk_fixed_put (GTK_FIXED (fixed18), R_AnnulerF_CDV, 96, 120);
  gtk_widget_set_size_request (R_AnnulerF_CDV, 74, 29);

  label37 = gtk_label_new (_("Selectionner l'identifiant du devis \303\240 annuler."));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed18), label37, 32, 8);
  gtk_widget_set_size_request (label37, 320, 56);

  AnnulerF_CDV = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (AnnulerF_CDV);
  gtk_fixed_put (GTK_FIXED (fixed18), AnnulerF_CDV, 248, 120);
  gtk_widget_set_size_request (AnnulerF_CDV, 70, 29);

  g_signal_connect ((gpointer) R_AnnulerF_CDV, "clicked",
                    G_CALLBACK (on_R_AnnulerF_CDV_clicked),
                    NULL);
  g_signal_connect ((gpointer) AnnulerF_CDV, "clicked",
                    G_CALLBACK (on_AnnulerF_CDV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WAnnuler_CDV, WAnnuler_CDV, "WAnnuler_CDV");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDV, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDV, comboboxACDV, "comboboxACDV");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDV, R_AnnulerF_CDV, "R_AnnulerF_CDV");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDV, label37, "label37");
  GLADE_HOOKUP_OBJECT (WAnnuler_CDV, AnnulerF_CDV, "AnnulerF_CDV");

  return WAnnuler_CDV;
}

GtkWidget*
create_WContinuer_CDH (void)
{
  GtkWidget *WContinuer_CDH;
  GtkWidget *fixed19;
  GtkWidget *comboboxCCDH;
  GtkWidget *label40;
  GtkWidget *ContinuerF_CDH;
  GtkWidget *R_ContinuerF_CDH;

  WContinuer_CDH = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (WContinuer_CDH), fixed19);

  comboboxCCDH = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxCCDH);
  gtk_fixed_put (GTK_FIXED (fixed19), comboboxCCDH, 96, 72);
  gtk_widget_set_size_request (comboboxCCDH, 150, 31);

  label40 = gtk_label_new (_("Selectionner l'identifiant du devis \303\240 payer."));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed19), label40, 32, 24);
  gtk_widget_set_size_request (label40, 336, 48);

  ContinuerF_CDH = gtk_button_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (ContinuerF_CDH);
  gtk_fixed_put (GTK_FIXED (fixed19), ContinuerF_CDH, 184, 120);
  gtk_widget_set_size_request (ContinuerF_CDH, 88, 32);

  R_ContinuerF_CDH = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_ContinuerF_CDH);
  gtk_fixed_put (GTK_FIXED (fixed19), R_ContinuerF_CDH, 88, 120);
  gtk_widget_set_size_request (R_ContinuerF_CDH, 80, 32);

  g_signal_connect ((gpointer) ContinuerF_CDH, "clicked",
                    G_CALLBACK (on_ContinuerF_CDH_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_ContinuerF_CDH, "clicked",
                    G_CALLBACK (on_R_ContinuerF_CDH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WContinuer_CDH, WContinuer_CDH, "WContinuer_CDH");
  GLADE_HOOKUP_OBJECT (WContinuer_CDH, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (WContinuer_CDH, comboboxCCDH, "comboboxCCDH");
  GLADE_HOOKUP_OBJECT (WContinuer_CDH, label40, "label40");
  GLADE_HOOKUP_OBJECT (WContinuer_CDH, ContinuerF_CDH, "ContinuerF_CDH");
  GLADE_HOOKUP_OBJECT (WContinuer_CDH, R_ContinuerF_CDH, "R_ContinuerF_CDH");

  return WContinuer_CDH;
}

GtkWidget*
create_WContinuer_CDE (void)
{
  GtkWidget *WContinuer_CDE;
  GtkWidget *fixed20;
  GtkWidget *comboboxCCDE;
  GtkWidget *label43;
  GtkWidget *ContinuerF_CDE;
  GtkWidget *R_ContinuerF_CDE;

  WContinuer_CDE = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (WContinuer_CDE), fixed20);

  comboboxCCDE = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxCCDE);
  gtk_fixed_put (GTK_FIXED (fixed20), comboboxCCDE, 80, 64);
  gtk_widget_set_size_request (comboboxCCDE, 155, 31);

  label43 = gtk_label_new (_("Selectionner l'identifiant du devis \303\240 payer."));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed20), label43, 24, 16);
  gtk_widget_set_size_request (label43, 336, 48);

  ContinuerF_CDE = gtk_button_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (ContinuerF_CDE);
  gtk_fixed_put (GTK_FIXED (fixed20), ContinuerF_CDE, 160, 120);
  gtk_widget_set_size_request (ContinuerF_CDE, 88, 32);

  R_ContinuerF_CDE = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_ContinuerF_CDE);
  gtk_fixed_put (GTK_FIXED (fixed20), R_ContinuerF_CDE, 64, 120);
  gtk_widget_set_size_request (R_ContinuerF_CDE, 80, 32);

  g_signal_connect ((gpointer) ContinuerF_CDE, "clicked",
                    G_CALLBACK (on_ContinuerF_CDE_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_ContinuerF_CDE, "clicked",
                    G_CALLBACK (on_R_ContinuerF_CDE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WContinuer_CDE, WContinuer_CDE, "WContinuer_CDE");
  GLADE_HOOKUP_OBJECT (WContinuer_CDE, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (WContinuer_CDE, comboboxCCDE, "comboboxCCDE");
  GLADE_HOOKUP_OBJECT (WContinuer_CDE, label43, "label43");
  GLADE_HOOKUP_OBJECT (WContinuer_CDE, ContinuerF_CDE, "ContinuerF_CDE");
  GLADE_HOOKUP_OBJECT (WContinuer_CDE, R_ContinuerF_CDE, "R_ContinuerF_CDE");

  return WContinuer_CDE;
}

GtkWidget*
create_WContinuer_CDV (void)
{
  GtkWidget *WContinuer_CDV;
  GtkWidget *fixed21;
  GtkWidget *comboboxCCDV;
  GtkWidget *label44;
  GtkWidget *ContinuerF_CDV;
  GtkWidget *R_ContinuerF_CDV;

  WContinuer_CDV = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_container_add (GTK_CONTAINER (WContinuer_CDV), fixed21);

  comboboxCCDV = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxCCDV);
  gtk_fixed_put (GTK_FIXED (fixed21), comboboxCCDV, 152, 96);
  gtk_widget_set_size_request (comboboxCCDV, 155, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxCCDV), _(" "));

  label44 = gtk_label_new (_("Selectionner l'identifiant du devis \303\240 payer."));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed21), label44, 64, 40);
  gtk_widget_set_size_request (label44, 336, 48);

  ContinuerF_CDV = gtk_button_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (ContinuerF_CDV);
  gtk_fixed_put (GTK_FIXED (fixed21), ContinuerF_CDV, 248, 144);
  gtk_widget_set_size_request (ContinuerF_CDV, 80, 32);

  R_ContinuerF_CDV = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_ContinuerF_CDV);
  gtk_fixed_put (GTK_FIXED (fixed21), R_ContinuerF_CDV, 144, 144);
  gtk_widget_set_size_request (R_ContinuerF_CDV, 74, 29);

  g_signal_connect ((gpointer) ContinuerF_CDV, "clicked",
                    G_CALLBACK (on_ContinuerF_CDV_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_ContinuerF_CDV, "clicked",
                    G_CALLBACK (on_R_ContinuerF_CDV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WContinuer_CDV, WContinuer_CDV, "WContinuer_CDV");
  GLADE_HOOKUP_OBJECT (WContinuer_CDV, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (WContinuer_CDV, comboboxCCDV, "comboboxCCDV");
  GLADE_HOOKUP_OBJECT (WContinuer_CDV, label44, "label44");
  GLADE_HOOKUP_OBJECT (WContinuer_CDV, ContinuerF_CDV, "ContinuerF_CDV");
  GLADE_HOOKUP_OBJECT (WContinuer_CDV, R_ContinuerF_CDV, "R_ContinuerF_CDV");

  return WContinuer_CDV;
}

GtkWidget*
create_WModifier_CDH (void)
{
  GtkWidget *WModifier_CDH;
  GtkWidget *fixed22;
  GtkWidget *entryreductionCDH;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *comboboxidMADH;
  GtkWidget *label55;
  GtkWidget *ValiderR_CDH;
  GtkWidget *R_ValiderR_CDH;

  WModifier_CDH = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (WModifier_CDH), fixed22);

  entryreductionCDH = gtk_entry_new ();
  gtk_widget_show (entryreductionCDH);
  gtk_fixed_put (GTK_FIXED (fixed22), entryreductionCDH, 112, 144);
  gtk_widget_set_size_request (entryreductionCDH, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryreductionCDH), 8226);

  label41 = gtk_label_new (_("Reduction de"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed22), label41, 0, 152);
  gtk_widget_set_size_request (label41, 104, 17);

  label42 = gtk_label_new (_("%"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed22), label42, 272, 152);
  gtk_widget_set_size_request (label42, 32, 16);

  comboboxidMADH = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxidMADH);
  gtk_fixed_put (GTK_FIXED (fixed22), comboboxidMADH, 80, 80);
  gtk_widget_set_size_request (comboboxidMADH, 155, 31);

  label55 = gtk_label_new (_("Selectionner id devis \303\240 modifier."));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed22), label55, 32, 24);
  gtk_widget_set_size_request (label55, 264, 48);

  ValiderR_CDH = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (ValiderR_CDH);
  gtk_fixed_put (GTK_FIXED (fixed22), ValiderR_CDH, 192, 200);
  gtk_widget_set_size_request (ValiderR_CDH, 74, 29);

  R_ValiderR_CDH = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_ValiderR_CDH);
  gtk_fixed_put (GTK_FIXED (fixed22), R_ValiderR_CDH, 72, 200);
  gtk_widget_set_size_request (R_ValiderR_CDH, 74, 29);

  g_signal_connect ((gpointer) ValiderR_CDH, "clicked",
                    G_CALLBACK (on_ValiderR_CDH_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_ValiderR_CDH, "clicked",
                    G_CALLBACK (on_R_ValiderR_CDH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WModifier_CDH, WModifier_CDH, "WModifier_CDH");
  GLADE_HOOKUP_OBJECT (WModifier_CDH, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (WModifier_CDH, entryreductionCDH, "entryreductionCDH");
  GLADE_HOOKUP_OBJECT (WModifier_CDH, label41, "label41");
  GLADE_HOOKUP_OBJECT (WModifier_CDH, label42, "label42");
  GLADE_HOOKUP_OBJECT (WModifier_CDH, comboboxidMADH, "comboboxidMADH");
  GLADE_HOOKUP_OBJECT (WModifier_CDH, label55, "label55");
  GLADE_HOOKUP_OBJECT (WModifier_CDH, ValiderR_CDH, "ValiderR_CDH");
  GLADE_HOOKUP_OBJECT (WModifier_CDH, R_ValiderR_CDH, "R_ValiderR_CDH");

  return WModifier_CDH;
}

GtkWidget*
create_WModifier_CDE (void)
{
  GtkWidget *WModifier_CDE;
  GtkWidget *fixed23;
  GtkWidget *entryreductionCDE;
  GtkWidget *label47;
  GtkWidget *label45;
  GtkWidget *comboboxidMADE;
  GtkWidget *label56;
  GtkWidget *R_ValiderR_CDE;
  GtkWidget *ValiderR_CDE;

  WModifier_CDE = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (WModifier_CDE), fixed23);

  entryreductionCDE = gtk_entry_new ();
  gtk_widget_show (entryreductionCDE);
  gtk_fixed_put (GTK_FIXED (fixed23), entryreductionCDE, 104, 128);
  gtk_widget_set_size_request (entryreductionCDE, 152, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryreductionCDE), 8226);

  label47 = gtk_label_new (_("%"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed23), label47, 256, 136);
  gtk_widget_set_size_request (label47, 32, 16);

  label45 = gtk_label_new (_("Reduction de"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed23), label45, 0, 136);
  gtk_widget_set_size_request (label45, 104, 17);

  comboboxidMADE = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxidMADE);
  gtk_fixed_put (GTK_FIXED (fixed23), comboboxidMADE, 72, 64);
  gtk_widget_set_size_request (comboboxidMADE, 155, 31);

  label56 = gtk_label_new (_("Selectionner id devis \303\240 modifier."));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed23), label56, 24, 8);
  gtk_widget_set_size_request (label56, 264, 48);

  R_ValiderR_CDE = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_ValiderR_CDE);
  gtk_fixed_put (GTK_FIXED (fixed23), R_ValiderR_CDE, 56, 184);
  gtk_widget_set_size_request (R_ValiderR_CDE, 74, 29);

  ValiderR_CDE = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (ValiderR_CDE);
  gtk_fixed_put (GTK_FIXED (fixed23), ValiderR_CDE, 192, 176);
  gtk_widget_set_size_request (ValiderR_CDE, 72, 32);

  g_signal_connect ((gpointer) R_ValiderR_CDE, "clicked",
                    G_CALLBACK (on_R_ValiderR_CDE_clicked),
                    NULL);
  g_signal_connect ((gpointer) ValiderR_CDE, "clicked",
                    G_CALLBACK (on_ValiderR_CDE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WModifier_CDE, WModifier_CDE, "WModifier_CDE");
  GLADE_HOOKUP_OBJECT (WModifier_CDE, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (WModifier_CDE, entryreductionCDE, "entryreductionCDE");
  GLADE_HOOKUP_OBJECT (WModifier_CDE, label47, "label47");
  GLADE_HOOKUP_OBJECT (WModifier_CDE, label45, "label45");
  GLADE_HOOKUP_OBJECT (WModifier_CDE, comboboxidMADE, "comboboxidMADE");
  GLADE_HOOKUP_OBJECT (WModifier_CDE, label56, "label56");
  GLADE_HOOKUP_OBJECT (WModifier_CDE, R_ValiderR_CDE, "R_ValiderR_CDE");
  GLADE_HOOKUP_OBJECT (WModifier_CDE, ValiderR_CDE, "ValiderR_CDE");

  return WModifier_CDE;
}

GtkWidget*
create_WModifier_CDV (void)
{
  GtkWidget *WModifier_CDV;
  GtkWidget *fixed24;
  GtkWidget *entryreductionCDV;
  GtkWidget *label48;
  GtkWidget *label46;
  GtkWidget *comboboxidMADV;
  GtkWidget *label57;
  GtkWidget *R_ValiderR_CDV;
  GtkWidget *ValiderR_CDV;

  WModifier_CDV = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (WModifier_CDV), fixed24);

  entryreductionCDV = gtk_entry_new ();
  gtk_widget_show (entryreductionCDV);
  gtk_fixed_put (GTK_FIXED (fixed24), entryreductionCDV, 104, 152);
  gtk_widget_set_size_request (entryreductionCDV, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryreductionCDV), 8226);

  label48 = gtk_label_new (_("%"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed24), label48, 272, 160);
  gtk_widget_set_size_request (label48, 32, 16);

  label46 = gtk_label_new (_("Reduction de"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed24), label46, 0, 160);
  gtk_widget_set_size_request (label46, 104, 17);

  comboboxidMADV = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxidMADV);
  gtk_fixed_put (GTK_FIXED (fixed24), comboboxidMADV, 72, 88);
  gtk_widget_set_size_request (comboboxidMADV, 155, 31);

  label57 = gtk_label_new (_("Selectionner id devis \303\240 modifier."));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed24), label57, 24, 24);
  gtk_widget_set_size_request (label57, 264, 48);

  R_ValiderR_CDV = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_ValiderR_CDV);
  gtk_fixed_put (GTK_FIXED (fixed24), R_ValiderR_CDV, 32, 200);
  gtk_widget_set_size_request (R_ValiderR_CDV, 74, 29);

  ValiderR_CDV = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (ValiderR_CDV);
  gtk_fixed_put (GTK_FIXED (fixed24), ValiderR_CDV, 160, 200);
  gtk_widget_set_size_request (ValiderR_CDV, 80, 32);

  g_signal_connect ((gpointer) R_ValiderR_CDV, "clicked",
                    G_CALLBACK (on_R_ValiderR_CDV_clicked),
                    NULL);
  g_signal_connect ((gpointer) ValiderR_CDV, "clicked",
                    G_CALLBACK (on_ValiderR_CDV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WModifier_CDV, WModifier_CDV, "WModifier_CDV");
  GLADE_HOOKUP_OBJECT (WModifier_CDV, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (WModifier_CDV, entryreductionCDV, "entryreductionCDV");
  GLADE_HOOKUP_OBJECT (WModifier_CDV, label48, "label48");
  GLADE_HOOKUP_OBJECT (WModifier_CDV, label46, "label46");
  GLADE_HOOKUP_OBJECT (WModifier_CDV, comboboxidMADV, "comboboxidMADV");
  GLADE_HOOKUP_OBJECT (WModifier_CDV, label57, "label57");
  GLADE_HOOKUP_OBJECT (WModifier_CDV, R_ValiderR_CDV, "R_ValiderR_CDV");
  GLADE_HOOKUP_OBJECT (WModifier_CDV, ValiderR_CDV, "ValiderR_CDV");

  return WModifier_CDV;
}

GtkWidget*
create_Reservation_annulerH (void)
{
  GtkWidget *Reservation_annulerH;
  GtkWidget *fixed25;
  GtkWidget *label49;
  GtkWidget *OKReservation_annulerH;

  Reservation_annulerH = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (Reservation_annulerH), fixed25);

  label49 = gtk_label_new (_("Reservation annul\303\251e"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed25), label49, 72, 24);
  gtk_widget_set_size_request (label49, 248, 48);

  OKReservation_annulerH = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKReservation_annulerH);
  gtk_fixed_put (GTK_FIXED (fixed25), OKReservation_annulerH, 152, 88);
  gtk_widget_set_size_request (OKReservation_annulerH, 74, 29);

  g_signal_connect ((gpointer) OKReservation_annulerH, "clicked",
                    G_CALLBACK (on_OKReservation_annulerH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reservation_annulerH, Reservation_annulerH, "Reservation_annulerH");
  GLADE_HOOKUP_OBJECT (Reservation_annulerH, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (Reservation_annulerH, label49, "label49");
  GLADE_HOOKUP_OBJECT (Reservation_annulerH, OKReservation_annulerH, "OKReservation_annulerH");

  return Reservation_annulerH;
}

GtkWidget*
create_Reduction_validerH (void)
{
  GtkWidget *Reduction_validerH;
  GtkWidget *fixed26;
  GtkWidget *label50;
  GtkWidget *OKReduction_validerH;

  Reduction_validerH = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_container_add (GTK_CONTAINER (Reduction_validerH), fixed26);

  label50 = gtk_label_new (_("R\303\251duction valid\303\251e"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed26), label50, 56, 16);
  gtk_widget_set_size_request (label50, 256, 56);

  OKReduction_validerH = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKReduction_validerH);
  gtk_fixed_put (GTK_FIXED (fixed26), OKReduction_validerH, 144, 80);
  gtk_widget_set_size_request (OKReduction_validerH, 74, 29);

  g_signal_connect ((gpointer) OKReduction_validerH, "clicked",
                    G_CALLBACK (on_OKReduction_validerH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reduction_validerH, Reduction_validerH, "Reduction_validerH");
  GLADE_HOOKUP_OBJECT (Reduction_validerH, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (Reduction_validerH, label50, "label50");
  GLADE_HOOKUP_OBJECT (Reduction_validerH, OKReduction_validerH, "OKReduction_validerH");

  return Reduction_validerH;
}

GtkWidget*
create_Reservation_annulerE (void)
{
  GtkWidget *Reservation_annulerE;
  GtkWidget *fixed27;
  GtkWidget *label51;
  GtkWidget *OKReservation_annulerE;

  Reservation_annulerE = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed27 = gtk_fixed_new ();
  gtk_widget_show (fixed27);
  gtk_container_add (GTK_CONTAINER (Reservation_annulerE), fixed27);

  label51 = gtk_label_new (_("Reservation annul\303\251e"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed27), label51, 64, 24);
  gtk_widget_set_size_request (label51, 248, 48);

  OKReservation_annulerE = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKReservation_annulerE);
  gtk_fixed_put (GTK_FIXED (fixed27), OKReservation_annulerE, 144, 72);
  gtk_widget_set_size_request (OKReservation_annulerE, 74, 29);

  g_signal_connect ((gpointer) OKReservation_annulerE, "clicked",
                    G_CALLBACK (on_OKReservation_annulerE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reservation_annulerE, Reservation_annulerE, "Reservation_annulerE");
  GLADE_HOOKUP_OBJECT (Reservation_annulerE, fixed27, "fixed27");
  GLADE_HOOKUP_OBJECT (Reservation_annulerE, label51, "label51");
  GLADE_HOOKUP_OBJECT (Reservation_annulerE, OKReservation_annulerE, "OKReservation_annulerE");

  return Reservation_annulerE;
}

GtkWidget*
create_Reservation_annulerV (void)
{
  GtkWidget *Reservation_annulerV;
  GtkWidget *fixed28;
  GtkWidget *label52;
  GtkWidget *OKReservation_annulerV;

  Reservation_annulerV = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed28 = gtk_fixed_new ();
  gtk_widget_show (fixed28);
  gtk_container_add (GTK_CONTAINER (Reservation_annulerV), fixed28);

  label52 = gtk_label_new (_("Reservation annul\303\251e"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed28), label52, 56, 24);
  gtk_widget_set_size_request (label52, 248, 48);

  OKReservation_annulerV = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKReservation_annulerV);
  gtk_fixed_put (GTK_FIXED (fixed28), OKReservation_annulerV, 144, 72);
  gtk_widget_set_size_request (OKReservation_annulerV, 74, 29);

  g_signal_connect ((gpointer) OKReservation_annulerV, "clicked",
                    G_CALLBACK (on_OKReservation_annulerV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reservation_annulerV, Reservation_annulerV, "Reservation_annulerV");
  GLADE_HOOKUP_OBJECT (Reservation_annulerV, fixed28, "fixed28");
  GLADE_HOOKUP_OBJECT (Reservation_annulerV, label52, "label52");
  GLADE_HOOKUP_OBJECT (Reservation_annulerV, OKReservation_annulerV, "OKReservation_annulerV");

  return Reservation_annulerV;
}

GtkWidget*
create_Reduction_validerE (void)
{
  GtkWidget *Reduction_validerE;
  GtkWidget *fixed29;
  GtkWidget *label53;
  GtkWidget *OKReduction_validerE;

  Reduction_validerE = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_container_add (GTK_CONTAINER (Reduction_validerE), fixed29);

  label53 = gtk_label_new (_("R\303\251duction valid\303\251e"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed29), label53, 64, 16);
  gtk_widget_set_size_request (label53, 256, 56);

  OKReduction_validerE = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKReduction_validerE);
  gtk_fixed_put (GTK_FIXED (fixed29), OKReduction_validerE, 168, 96);
  gtk_widget_set_size_request (OKReduction_validerE, 74, 29);

  g_signal_connect ((gpointer) OKReduction_validerE, "clicked",
                    G_CALLBACK (on_OKReduction_validerE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reduction_validerE, Reduction_validerE, "Reduction_validerE");
  GLADE_HOOKUP_OBJECT (Reduction_validerE, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (Reduction_validerE, label53, "label53");
  GLADE_HOOKUP_OBJECT (Reduction_validerE, OKReduction_validerE, "OKReduction_validerE");

  return Reduction_validerE;
}

GtkWidget*
create_Reduction_validerV (void)
{
  GtkWidget *Reduction_validerV;
  GtkWidget *fixed30;
  GtkWidget *label54;
  GtkWidget *OKReduction_validerV;

  Reduction_validerV = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_container_add (GTK_CONTAINER (Reduction_validerV), fixed30);

  label54 = gtk_label_new (_("R\303\251duction valid\303\251e"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed30), label54, 64, 16);
  gtk_widget_set_size_request (label54, 256, 56);

  OKReduction_validerV = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKReduction_validerV);
  gtk_fixed_put (GTK_FIXED (fixed30), OKReduction_validerV, 144, 96);
  gtk_widget_set_size_request (OKReduction_validerV, 74, 29);

  g_signal_connect ((gpointer) OKReduction_validerV, "clicked",
                    G_CALLBACK (on_OKReduction_validerV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reduction_validerV, Reduction_validerV, "Reduction_validerV");
  GLADE_HOOKUP_OBJECT (Reduction_validerV, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (Reduction_validerV, label54, "label54");
  GLADE_HOOKUP_OBJECT (Reduction_validerV, OKReduction_validerV, "OKReduction_validerV");

  return Reduction_validerV;
}

GtkWidget*
create_Window (void)
{
  GtkWidget *Window;
  GtkWidget *fixed31;
  GtkWidget *button;

  Window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Window), _("window"));

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_container_add (GTK_CONTAINER (Window), fixed31);

  button = gtk_button_new_with_mnemonic (_("button"));
  gtk_widget_show (button);
  gtk_fixed_put (GTK_FIXED (fixed31), button, 152, 112);
  gtk_widget_set_size_request (button, 66, 29);

  g_signal_connect ((gpointer) button, "clicked",
                    G_CALLBACK (on_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Window, Window, "Window");
  GLADE_HOOKUP_OBJECT (Window, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (Window, button, "button");

  return Window;
}

GtkWidget*
create_Facpayee (void)
{
  GtkWidget *Facpayee;
  GtkWidget *fixed32;
  GtkWidget *label58;

  Facpayee = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed32 = gtk_fixed_new ();
  gtk_widget_show (fixed32);
  gtk_container_add (GTK_CONTAINER (Facpayee), fixed32);

  label58 = gtk_label_new (_("Facture pay\303\251e ."));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed32), label58, 120, 104);
  gtk_widget_set_size_request (label58, 160, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Facpayee, Facpayee, "Facpayee");
  GLADE_HOOKUP_OBJECT (Facpayee, fixed32, "fixed32");
  GLADE_HOOKUP_OBJECT (Facpayee, label58, "label58");

  return Facpayee;
}

GtkWidget*
create_bienvenueespece (void)
{
  GtkWidget *bienvenueespece;
  GtkWidget *fixed33;
  GtkWidget *label59;
  GtkWidget *OKcodeespece;

  bienvenueespece = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed33 = gtk_fixed_new ();
  gtk_widget_show (fixed33);
  gtk_container_add (GTK_CONTAINER (bienvenueespece), fixed33);

  label59 = gtk_label_new (_("Vous devez contactez notre agence SkyTravel."));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed33), label59, 16, 8);
  gtk_widget_set_size_request (label59, 368, 72);

  OKcodeespece = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (OKcodeespece);
  gtk_fixed_put (GTK_FIXED (fixed33), OKcodeespece, 144, 72);
  gtk_widget_set_size_request (OKcodeespece, 66, 29);

  g_signal_connect ((gpointer) OKcodeespece, "clicked",
                    G_CALLBACK (on_OKcodeespece_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bienvenueespece, bienvenueespece, "bienvenueespece");
  GLADE_HOOKUP_OBJECT (bienvenueespece, fixed33, "fixed33");
  GLADE_HOOKUP_OBJECT (bienvenueespece, label59, "label59");
  GLADE_HOOKUP_OBJECT (bienvenueespece, OKcodeespece, "OKcodeespece");

  return bienvenueespece;
}

GtkWidget*
create_mode_payement (void)
{
  GtkWidget *mode_payement;
  GtkWidget *fixed34;
  GtkWidget *iddevisMP;
  GtkWidget *label65;
  GtkWidget *label60;
  GtkWidget *comboboxmodepayement;
  GtkWidget *Validermodepayement;
  GtkWidget *R_validermodepayement;

  mode_payement = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed34 = gtk_fixed_new ();
  gtk_widget_show (fixed34);
  gtk_container_add (GTK_CONTAINER (mode_payement), fixed34);

  iddevisMP = gtk_entry_new ();
  gtk_widget_show (iddevisMP);
  gtk_fixed_put (GTK_FIXED (fixed34), iddevisMP, 112, 80);
  gtk_widget_set_size_request (iddevisMP, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (iddevisMP), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (iddevisMP), 8226);

  label65 = gtk_label_new (_("Id devis"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed34), label65, 24, 80);
  gtk_widget_set_size_request (label65, 72, 16);

  label60 = gtk_label_new (_("Mode payement."));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed34), label60, 24, 0);
  gtk_widget_set_size_request (label60, 280, 72);

  comboboxmodepayement = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxmodepayement);
  gtk_fixed_put (GTK_FIXED (fixed34), comboboxmodepayement, 80, 120);
  gtk_widget_set_size_request (comboboxmodepayement, 192, 48);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodepayement), _("Espece"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodepayement), _("Carte visa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodepayement), _("Carte e-dinar"));

  Validermodepayement = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (Validermodepayement);
  gtk_fixed_put (GTK_FIXED (fixed34), Validermodepayement, 208, 192);
  gtk_widget_set_size_request (Validermodepayement, 66, 29);

  R_validermodepayement = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_validermodepayement);
  gtk_fixed_put (GTK_FIXED (fixed34), R_validermodepayement, 96, 192);
  gtk_widget_set_size_request (R_validermodepayement, 66, 29);

  g_signal_connect ((gpointer) Validermodepayement, "clicked",
                    G_CALLBACK (on_Validermodepayement_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_validermodepayement, "clicked",
                    G_CALLBACK (on_R_validermodepayement_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mode_payement, mode_payement, "mode_payement");
  GLADE_HOOKUP_OBJECT (mode_payement, fixed34, "fixed34");
  GLADE_HOOKUP_OBJECT (mode_payement, iddevisMP, "iddevisMP");
  GLADE_HOOKUP_OBJECT (mode_payement, label65, "label65");
  GLADE_HOOKUP_OBJECT (mode_payement, label60, "label60");
  GLADE_HOOKUP_OBJECT (mode_payement, comboboxmodepayement, "comboboxmodepayement");
  GLADE_HOOKUP_OBJECT (mode_payement, Validermodepayement, "Validermodepayement");
  GLADE_HOOKUP_OBJECT (mode_payement, R_validermodepayement, "R_validermodepayement");

  return mode_payement;
}

GtkWidget*
create_Payement (void)
{
  GtkWidget *Payement;
  GtkWidget *fixed35;
  GtkWidget *entryidcartepayement;
  GtkWidget *entrycodesecretpayement;
  GtkWidget *entrymontantpayementF;
  GtkObject *dateexpiration_jour_adj;
  GtkWidget *dateexpiration_jour;
  GtkObject *dateexpiration_mois_adj;
  GtkWidget *dateexpiration_mois;
  GtkObject *dateexpiration_annee_adj;
  GtkWidget *dateexpiration_annee;
  GtkWidget *label64;
  GtkWidget *label63;
  GtkWidget *label61;
  GtkWidget *label66;
  GtkWidget *iddevispayement;
  GtkWidget *label62;
  GtkWidget *PayerF;
  GtkWidget *R_payerF;

  Payement = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed35 = gtk_fixed_new ();
  gtk_widget_show (fixed35);
  gtk_container_add (GTK_CONTAINER (Payement), fixed35);

  entryidcartepayement = gtk_entry_new ();
  gtk_widget_show (entryidcartepayement);
  gtk_fixed_put (GTK_FIXED (fixed35), entryidcartepayement, 136, 56);
  gtk_widget_set_size_request (entryidcartepayement, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidcartepayement), 8226);

  entrycodesecretpayement = gtk_entry_new ();
  gtk_widget_show (entrycodesecretpayement);
  gtk_fixed_put (GTK_FIXED (fixed35), entrycodesecretpayement, 152, 168);
  gtk_widget_set_size_request (entrycodesecretpayement, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrycodesecretpayement), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycodesecretpayement), 8226);

  entrymontantpayementF = gtk_entry_new ();
  gtk_widget_show (entrymontantpayementF);
  gtk_fixed_put (GTK_FIXED (fixed35), entrymontantpayementF, 152, 216);
  gtk_widget_set_size_request (entrymontantpayementF, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymontantpayementF), 8226);

  dateexpiration_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  dateexpiration_jour = gtk_spin_button_new (GTK_ADJUSTMENT (dateexpiration_jour_adj), 1, 0);
  gtk_widget_show (dateexpiration_jour);
  gtk_fixed_put (GTK_FIXED (fixed35), dateexpiration_jour, 144, 112);
  gtk_widget_set_size_request (dateexpiration_jour, 60, 27);

  dateexpiration_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  dateexpiration_mois = gtk_spin_button_new (GTK_ADJUSTMENT (dateexpiration_mois_adj), 1, 0);
  gtk_widget_show (dateexpiration_mois);
  gtk_fixed_put (GTK_FIXED (fixed35), dateexpiration_mois, 216, 112);
  gtk_widget_set_size_request (dateexpiration_mois, 60, 27);

  dateexpiration_annee_adj = gtk_adjustment_new (1, 2019, 2999, 1, 10, 10);
  dateexpiration_annee = gtk_spin_button_new (GTK_ADJUSTMENT (dateexpiration_annee_adj), 1, 0);
  gtk_widget_show (dateexpiration_annee);
  gtk_fixed_put (GTK_FIXED (fixed35), dateexpiration_annee, 296, 112);
  gtk_widget_set_size_request (dateexpiration_annee, 60, 27);

  label64 = gtk_label_new (_("Montant :"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed35), label64, 16, 216);
  gtk_widget_set_size_request (label64, 80, 16);

  label63 = gtk_label_new (_("Code secret :"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed35), label63, 8, 168);
  gtk_widget_set_size_request (label63, 96, 16);

  label61 = gtk_label_new (_("Date d'expiration :"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed35), label61, 0, 120);
  gtk_widget_set_size_request (label61, 128, 16);

  label66 = gtk_label_new (_("Id devis"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed35), label66, 16, 16);
  gtk_widget_set_size_request (label66, 72, 16);

  iddevispayement = gtk_entry_new ();
  gtk_widget_show (iddevispayement);
  gtk_fixed_put (GTK_FIXED (fixed35), iddevispayement, 136, 8);
  gtk_widget_set_size_request (iddevispayement, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (iddevispayement), 8226);

  label62 = gtk_label_new (_("Id carte :"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed35), label62, 16, 64);
  gtk_widget_set_size_request (label62, 72, 16);

  PayerF = gtk_button_new_with_mnemonic (_("Payer"));
  gtk_widget_show (PayerF);
  gtk_fixed_put (GTK_FIXED (fixed35), PayerF, 224, 256);
  gtk_widget_set_size_request (PayerF, 66, 29);

  R_payerF = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_payerF);
  gtk_fixed_put (GTK_FIXED (fixed35), R_payerF, 72, 256);
  gtk_widget_set_size_request (R_payerF, 66, 29);

  g_signal_connect ((gpointer) PayerF, "clicked",
                    G_CALLBACK (on_PayerF_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_payerF, "clicked",
                    G_CALLBACK (on_R_payerF_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Payement, Payement, "Payement");
  GLADE_HOOKUP_OBJECT (Payement, fixed35, "fixed35");
  GLADE_HOOKUP_OBJECT (Payement, entryidcartepayement, "entryidcartepayement");
  GLADE_HOOKUP_OBJECT (Payement, entrycodesecretpayement, "entrycodesecretpayement");
  GLADE_HOOKUP_OBJECT (Payement, entrymontantpayementF, "entrymontantpayementF");
  GLADE_HOOKUP_OBJECT (Payement, dateexpiration_jour, "dateexpiration_jour");
  GLADE_HOOKUP_OBJECT (Payement, dateexpiration_mois, "dateexpiration_mois");
  GLADE_HOOKUP_OBJECT (Payement, dateexpiration_annee, "dateexpiration_annee");
  GLADE_HOOKUP_OBJECT (Payement, label64, "label64");
  GLADE_HOOKUP_OBJECT (Payement, label63, "label63");
  GLADE_HOOKUP_OBJECT (Payement, label61, "label61");
  GLADE_HOOKUP_OBJECT (Payement, label66, "label66");
  GLADE_HOOKUP_OBJECT (Payement, iddevispayement, "iddevispayement");
  GLADE_HOOKUP_OBJECT (Payement, label62, "label62");
  GLADE_HOOKUP_OBJECT (Payement, PayerF, "PayerF");
  GLADE_HOOKUP_OBJECT (Payement, R_payerF, "R_payerF");

  return Payement;
}

GtkWidget*
create_mode_payement_E (void)
{
  GtkWidget *mode_payement_E;
  GtkWidget *fixed36;
  GtkWidget *label68;
  GtkWidget *label69;
  GtkWidget *iddevisMPE;
  GtkWidget *ValidermodepayementE;
  GtkWidget *comboboxmodepayementE;
  GtkWidget *R_validermodepayementE;

  mode_payement_E = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed36 = gtk_fixed_new ();
  gtk_widget_show (fixed36);
  gtk_container_add (GTK_CONTAINER (mode_payement_E), fixed36);

  label68 = gtk_label_new (_("Mode payement"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed36), label68, 80, 16);
  gtk_widget_set_size_request (label68, 216, 32);

  label69 = gtk_label_new (_("Id devis"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed36), label69, 8, 72);
  gtk_widget_set_size_request (label69, 96, 32);

  iddevisMPE = gtk_entry_new ();
  gtk_widget_show (iddevisMPE);
  gtk_fixed_put (GTK_FIXED (fixed36), iddevisMPE, 112, 72);
  gtk_widget_set_size_request (iddevisMPE, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (iddevisMPE), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (iddevisMPE), 8226);

  ValidermodepayementE = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (ValidermodepayementE);
  gtk_fixed_put (GTK_FIXED (fixed36), ValidermodepayementE, 216, 248);
  gtk_widget_set_size_request (ValidermodepayementE, 66, 29);

  comboboxmodepayementE = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxmodepayementE);
  gtk_fixed_put (GTK_FIXED (fixed36), comboboxmodepayementE, 80, 136);
  gtk_widget_set_size_request (comboboxmodepayementE, 200, 56);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodepayementE), _("Espece"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodepayementE), _("Carte visa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodepayementE), _("Carte e-dinar"));

  R_validermodepayementE = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_validermodepayementE);
  gtk_fixed_put (GTK_FIXED (fixed36), R_validermodepayementE, 72, 248);
  gtk_widget_set_size_request (R_validermodepayementE, 66, 29);

  g_signal_connect ((gpointer) ValidermodepayementE, "clicked",
                    G_CALLBACK (on_ValidermodepayementE_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_validermodepayementE, "clicked",
                    G_CALLBACK (on_R_validermodepayementE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mode_payement_E, mode_payement_E, "mode_payement_E");
  GLADE_HOOKUP_OBJECT (mode_payement_E, fixed36, "fixed36");
  GLADE_HOOKUP_OBJECT (mode_payement_E, label68, "label68");
  GLADE_HOOKUP_OBJECT (mode_payement_E, label69, "label69");
  GLADE_HOOKUP_OBJECT (mode_payement_E, iddevisMPE, "iddevisMPE");
  GLADE_HOOKUP_OBJECT (mode_payement_E, ValidermodepayementE, "ValidermodepayementE");
  GLADE_HOOKUP_OBJECT (mode_payement_E, comboboxmodepayementE, "comboboxmodepayementE");
  GLADE_HOOKUP_OBJECT (mode_payement_E, R_validermodepayementE, "R_validermodepayementE");

  return mode_payement_E;
}

GtkWidget*
create_mode_payement_V (void)
{
  GtkWidget *mode_payement_V;
  GtkWidget *fixed37;
  GtkWidget *label70;
  GtkWidget *label71;
  GtkWidget *iddevisMPV;
  GtkWidget *comboboxmodepayementV;
  GtkWidget *ValidermodepayementV;
  GtkWidget *R_validermodepayementV;

  mode_payement_V = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed37 = gtk_fixed_new ();
  gtk_widget_show (fixed37);
  gtk_container_add (GTK_CONTAINER (mode_payement_V), fixed37);

  label70 = gtk_label_new (_("Mode payement"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed37), label70, 104, 8);
  gtk_widget_set_size_request (label70, 176, 40);

  label71 = gtk_label_new (_("Id devis"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed37), label71, 8, 64);
  gtk_widget_set_size_request (label71, 96, 32);

  iddevisMPV = gtk_entry_new ();
  gtk_widget_show (iddevisMPV);
  gtk_fixed_put (GTK_FIXED (fixed37), iddevisMPV, 112, 64);
  gtk_widget_set_size_request (iddevisMPV, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (iddevisMPV), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (iddevisMPV), 8226);

  comboboxmodepayementV = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxmodepayementV);
  gtk_fixed_put (GTK_FIXED (fixed37), comboboxmodepayementV, 88, 112);
  gtk_widget_set_size_request (comboboxmodepayementV, 200, 56);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodepayementV), _("Espece"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodepayementV), _("Carte visa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodepayementV), _("Carte e-dinar"));

  ValidermodepayementV = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (ValidermodepayementV);
  gtk_fixed_put (GTK_FIXED (fixed37), ValidermodepayementV, 232, 192);
  gtk_widget_set_size_request (ValidermodepayementV, 66, 29);

  R_validermodepayementV = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_validermodepayementV);
  gtk_fixed_put (GTK_FIXED (fixed37), R_validermodepayementV, 96, 192);
  gtk_widget_set_size_request (R_validermodepayementV, 66, 29);

  g_signal_connect ((gpointer) ValidermodepayementV, "clicked",
                    G_CALLBACK (on_ValidermodepayementV_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_validermodepayementV, "clicked",
                    G_CALLBACK (on_R_validermodepayementE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mode_payement_V, mode_payement_V, "mode_payement_V");
  GLADE_HOOKUP_OBJECT (mode_payement_V, fixed37, "fixed37");
  GLADE_HOOKUP_OBJECT (mode_payement_V, label70, "label70");
  GLADE_HOOKUP_OBJECT (mode_payement_V, label71, "label71");
  GLADE_HOOKUP_OBJECT (mode_payement_V, iddevisMPV, "iddevisMPV");
  GLADE_HOOKUP_OBJECT (mode_payement_V, comboboxmodepayementV, "comboboxmodepayementV");
  GLADE_HOOKUP_OBJECT (mode_payement_V, ValidermodepayementV, "ValidermodepayementV");
  GLADE_HOOKUP_OBJECT (mode_payement_V, R_validermodepayementV, "R_validermodepayementV");

  return mode_payement_V;
}

GtkWidget*
create_PayementE (void)
{
  GtkWidget *PayementE;
  GtkWidget *fixed39;
  GtkWidget *entryidcartepayementE;
  GtkWidget *entrycodesecretpayementE;
  GtkWidget *entrymontantpayementFE;
  GtkObject *dateexpiration_jourE_adj;
  GtkWidget *dateexpiration_jourE;
  GtkObject *dateexpiration_moisE_adj;
  GtkWidget *dateexpiration_moisE;
  GtkObject *dateexpiration_anneeE_adj;
  GtkWidget *dateexpiration_anneeE;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *label83;
  GtkWidget *label84;
  GtkWidget *iddevispayementE;
  GtkWidget *label85;
  GtkWidget *PayerFE;
  GtkWidget *R_payerFE;

  PayementE = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed39 = gtk_fixed_new ();
  gtk_widget_show (fixed39);
  gtk_container_add (GTK_CONTAINER (PayementE), fixed39);

  entryidcartepayementE = gtk_entry_new ();
  gtk_widget_show (entryidcartepayementE);
  gtk_fixed_put (GTK_FIXED (fixed39), entryidcartepayementE, 136, 56);
  gtk_widget_set_size_request (entryidcartepayementE, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidcartepayementE), 8226);

  entrycodesecretpayementE = gtk_entry_new ();
  gtk_widget_show (entrycodesecretpayementE);
  gtk_fixed_put (GTK_FIXED (fixed39), entrycodesecretpayementE, 152, 168);
  gtk_widget_set_size_request (entrycodesecretpayementE, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrycodesecretpayementE), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycodesecretpayementE), 8226);

  entrymontantpayementFE = gtk_entry_new ();
  gtk_widget_show (entrymontantpayementFE);
  gtk_fixed_put (GTK_FIXED (fixed39), entrymontantpayementFE, 152, 216);
  gtk_widget_set_size_request (entrymontantpayementFE, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entrymontantpayementFE), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymontantpayementFE), 8226);

  dateexpiration_jourE_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  dateexpiration_jourE = gtk_spin_button_new (GTK_ADJUSTMENT (dateexpiration_jourE_adj), 1, 0);
  gtk_widget_show (dateexpiration_jourE);
  gtk_fixed_put (GTK_FIXED (fixed39), dateexpiration_jourE, 144, 112);
  gtk_widget_set_size_request (dateexpiration_jourE, 60, 27);

  dateexpiration_moisE_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  dateexpiration_moisE = gtk_spin_button_new (GTK_ADJUSTMENT (dateexpiration_moisE_adj), 1, 0);
  gtk_widget_show (dateexpiration_moisE);
  gtk_fixed_put (GTK_FIXED (fixed39), dateexpiration_moisE, 216, 112);
  gtk_widget_set_size_request (dateexpiration_moisE, 60, 27);

  dateexpiration_anneeE_adj = gtk_adjustment_new (1, 2019, 2999, 1, 10, 10);
  dateexpiration_anneeE = gtk_spin_button_new (GTK_ADJUSTMENT (dateexpiration_anneeE_adj), 1, 0);
  gtk_widget_show (dateexpiration_anneeE);
  gtk_fixed_put (GTK_FIXED (fixed39), dateexpiration_anneeE, 296, 112);
  gtk_widget_set_size_request (dateexpiration_anneeE, 60, 27);

  label81 = gtk_label_new (_("Montant :"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed39), label81, 16, 216);
  gtk_widget_set_size_request (label81, 80, 16);

  label82 = gtk_label_new (_("Code secret :"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed39), label82, 8, 168);
  gtk_widget_set_size_request (label82, 96, 16);

  label83 = gtk_label_new (_("Date d'expiration :"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed39), label83, 0, 120);
  gtk_widget_set_size_request (label83, 128, 16);

  label84 = gtk_label_new (_("Id devis"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed39), label84, 16, 16);
  gtk_widget_set_size_request (label84, 72, 16);

  iddevispayementE = gtk_entry_new ();
  gtk_widget_show (iddevispayementE);
  gtk_fixed_put (GTK_FIXED (fixed39), iddevispayementE, 136, 8);
  gtk_widget_set_size_request (iddevispayementE, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (iddevispayementE), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (iddevispayementE), 8226);

  label85 = gtk_label_new (_("Id carte :"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed39), label85, 16, 64);
  gtk_widget_set_size_request (label85, 72, 16);

  PayerFE = gtk_button_new_with_mnemonic (_("Payer"));
  gtk_widget_show (PayerFE);
  gtk_fixed_put (GTK_FIXED (fixed39), PayerFE, 232, 256);
  gtk_widget_set_size_request (PayerFE, 74, 29);

  R_payerFE = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_payerFE);
  gtk_fixed_put (GTK_FIXED (fixed39), R_payerFE, 56, 256);
  gtk_widget_set_size_request (R_payerFE, 74, 29);

  g_signal_connect ((gpointer) PayerFE, "clicked",
                    G_CALLBACK (on_PayerFE_clicked),
                    NULL);
  g_signal_connect ((gpointer) R_payerFE, "clicked",
                    G_CALLBACK (on_R_payerFE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (PayementE, PayementE, "PayementE");
  GLADE_HOOKUP_OBJECT (PayementE, fixed39, "fixed39");
  GLADE_HOOKUP_OBJECT (PayementE, entryidcartepayementE, "entryidcartepayementE");
  GLADE_HOOKUP_OBJECT (PayementE, entrycodesecretpayementE, "entrycodesecretpayementE");
  GLADE_HOOKUP_OBJECT (PayementE, entrymontantpayementFE, "entrymontantpayementFE");
  GLADE_HOOKUP_OBJECT (PayementE, dateexpiration_jourE, "dateexpiration_jourE");
  GLADE_HOOKUP_OBJECT (PayementE, dateexpiration_moisE, "dateexpiration_moisE");
  GLADE_HOOKUP_OBJECT (PayementE, dateexpiration_anneeE, "dateexpiration_anneeE");
  GLADE_HOOKUP_OBJECT (PayementE, label81, "label81");
  GLADE_HOOKUP_OBJECT (PayementE, label82, "label82");
  GLADE_HOOKUP_OBJECT (PayementE, label83, "label83");
  GLADE_HOOKUP_OBJECT (PayementE, label84, "label84");
  GLADE_HOOKUP_OBJECT (PayementE, iddevispayementE, "iddevispayementE");
  GLADE_HOOKUP_OBJECT (PayementE, label85, "label85");
  GLADE_HOOKUP_OBJECT (PayementE, PayerFE, "PayerFE");
  GLADE_HOOKUP_OBJECT (PayementE, R_payerFE, "R_payerFE");

  return PayementE;
}

GtkWidget*
create_PayementV (void)
{
  GtkWidget *PayementV;
  GtkWidget *fixed40;
  GtkWidget *entryidcartepayementV;
  GtkWidget *entrycodesecretpayementV;
  GtkWidget *entrymontantpayementFV;
  GtkObject *dateexpiration_jourV_adj;
  GtkWidget *dateexpiration_jourV;
  GtkObject *dateexpiration_moisV_adj;
  GtkWidget *dateexpiration_moisV;
  GtkObject *dateexpiration_anneeV_adj;
  GtkWidget *dateexpiration_anneeV;
  GtkWidget *label86;
  GtkWidget *label87;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *iddevispayementV;
  GtkWidget *label90;
  GtkWidget *R_payerFV;
  GtkWidget *PayerFV;

  PayementV = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed40 = gtk_fixed_new ();
  gtk_widget_show (fixed40);
  gtk_container_add (GTK_CONTAINER (PayementV), fixed40);

  entryidcartepayementV = gtk_entry_new ();
  gtk_widget_show (entryidcartepayementV);
  gtk_fixed_put (GTK_FIXED (fixed40), entryidcartepayementV, 136, 56);
  gtk_widget_set_size_request (entryidcartepayementV, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidcartepayementV), 8226);

  entrycodesecretpayementV = gtk_entry_new ();
  gtk_widget_show (entrycodesecretpayementV);
  gtk_fixed_put (GTK_FIXED (fixed40), entrycodesecretpayementV, 152, 168);
  gtk_widget_set_size_request (entrycodesecretpayementV, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrycodesecretpayementV), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycodesecretpayementV), 8226);

  entrymontantpayementFV = gtk_entry_new ();
  gtk_widget_show (entrymontantpayementFV);
  gtk_fixed_put (GTK_FIXED (fixed40), entrymontantpayementFV, 152, 208);
  gtk_widget_set_size_request (entrymontantpayementFV, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entrymontantpayementFV), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymontantpayementFV), 8226);

  dateexpiration_jourV_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  dateexpiration_jourV = gtk_spin_button_new (GTK_ADJUSTMENT (dateexpiration_jourV_adj), 1, 0);
  gtk_widget_show (dateexpiration_jourV);
  gtk_fixed_put (GTK_FIXED (fixed40), dateexpiration_jourV, 144, 112);
  gtk_widget_set_size_request (dateexpiration_jourV, 60, 27);

  dateexpiration_moisV_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  dateexpiration_moisV = gtk_spin_button_new (GTK_ADJUSTMENT (dateexpiration_moisV_adj), 1, 0);
  gtk_widget_show (dateexpiration_moisV);
  gtk_fixed_put (GTK_FIXED (fixed40), dateexpiration_moisV, 216, 112);
  gtk_widget_set_size_request (dateexpiration_moisV, 60, 27);

  dateexpiration_anneeV_adj = gtk_adjustment_new (1, 2019, 2999, 1, 10, 10);
  dateexpiration_anneeV = gtk_spin_button_new (GTK_ADJUSTMENT (dateexpiration_anneeV_adj), 1, 0);
  gtk_widget_show (dateexpiration_anneeV);
  gtk_fixed_put (GTK_FIXED (fixed40), dateexpiration_anneeV, 296, 112);
  gtk_widget_set_size_request (dateexpiration_anneeV, 60, 27);

  label86 = gtk_label_new (_("Montant :"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed40), label86, 16, 216);
  gtk_widget_set_size_request (label86, 80, 16);

  label87 = gtk_label_new (_("Code secret :"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed40), label87, 8, 168);
  gtk_widget_set_size_request (label87, 96, 16);

  label88 = gtk_label_new (_("Date d'expiration :"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed40), label88, 0, 120);
  gtk_widget_set_size_request (label88, 128, 16);

  label89 = gtk_label_new (_("Id devis"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed40), label89, 16, 16);
  gtk_widget_set_size_request (label89, 72, 16);

  iddevispayementV = gtk_entry_new ();
  gtk_widget_show (iddevispayementV);
  gtk_fixed_put (GTK_FIXED (fixed40), iddevispayementV, 136, 8);
  gtk_widget_set_size_request (iddevispayementV, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (iddevispayementV), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (iddevispayementV), 8226);

  label90 = gtk_label_new (_("Id carte :"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed40), label90, 16, 64);
  gtk_widget_set_size_request (label90, 72, 16);

  R_payerFV = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (R_payerFV);
  gtk_fixed_put (GTK_FIXED (fixed40), R_payerFV, 72, 256);
  gtk_widget_set_size_request (R_payerFV, 74, 29);

  PayerFV = gtk_button_new_with_mnemonic (_("Payer"));
  gtk_widget_show (PayerFV);
  gtk_fixed_put (GTK_FIXED (fixed40), PayerFV, 216, 256);
  gtk_widget_set_size_request (PayerFV, 74, 29);

  g_signal_connect ((gpointer) R_payerFV, "clicked",
                    G_CALLBACK (on_R_payerFV_clicked),
                    NULL);
  g_signal_connect ((gpointer) PayerFV, "clicked",
                    G_CALLBACK (on_PayerFV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (PayementV, PayementV, "PayementV");
  GLADE_HOOKUP_OBJECT (PayementV, fixed40, "fixed40");
  GLADE_HOOKUP_OBJECT (PayementV, entryidcartepayementV, "entryidcartepayementV");
  GLADE_HOOKUP_OBJECT (PayementV, entrycodesecretpayementV, "entrycodesecretpayementV");
  GLADE_HOOKUP_OBJECT (PayementV, entrymontantpayementFV, "entrymontantpayementFV");
  GLADE_HOOKUP_OBJECT (PayementV, dateexpiration_jourV, "dateexpiration_jourV");
  GLADE_HOOKUP_OBJECT (PayementV, dateexpiration_moisV, "dateexpiration_moisV");
  GLADE_HOOKUP_OBJECT (PayementV, dateexpiration_anneeV, "dateexpiration_anneeV");
  GLADE_HOOKUP_OBJECT (PayementV, label86, "label86");
  GLADE_HOOKUP_OBJECT (PayementV, label87, "label87");
  GLADE_HOOKUP_OBJECT (PayementV, label88, "label88");
  GLADE_HOOKUP_OBJECT (PayementV, label89, "label89");
  GLADE_HOOKUP_OBJECT (PayementV, iddevispayementV, "iddevispayementV");
  GLADE_HOOKUP_OBJECT (PayementV, label90, "label90");
  GLADE_HOOKUP_OBJECT (PayementV, R_payerFV, "R_payerFV");
  GLADE_HOOKUP_OBJECT (PayementV, PayerFV, "PayerFV");

  return PayementV;
}

