/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification_utilisateur (void);
GtkWidget* create_confirmation_authentification_admin (void);
GtkWidget* create_espace_admin (void);
GtkWidget* create_espace_employee (void);
GtkWidget* create_espace_client (void);
GtkWidget* create_ajouter_employee (void);
GtkWidget* create_supprimer_employee (void);
GtkWidget* create_confirmation_ajouter_employee (void);
GtkWidget* create_confirmation_authentification_employee (void);
GtkWidget* create_confirmation_authentification_client (void);
GtkWidget* create_confirmation_supprimer_employee (void);
GtkWidget* create_modifier_employee (void);
GtkWidget* create_confirmation_modifier_employee (void);
GtkWidget* create_ajouter_client_admin (void);
GtkWidget* create_confirmation_ajouter_client_admin (void);
GtkWidget* create_supprimer_client_admin (void);
GtkWidget* create_confirmation_supprimer_client_admin (void);
GtkWidget* create_modifier_client_admin (void);
GtkWidget* create_confirmation_modifier_client_admin (void);
GtkWidget* create_ajouter_client_employee (void);
GtkWidget* create_confirmation_ajouter_client_employee (void);
GtkWidget* create_modifier_client_employee (void);
GtkWidget* create_confirmation_modifier_client_employee (void);
GtkWidget* create_supprimer_client_employee (void);
GtkWidget* create_confirmation_supprimer_client_employee (void);
