/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *authentification_utilisateur;
  GtkWidget *confirmation_authentification_admin;
  GtkWidget *espace_admin;
  GtkWidget *espace_employee;
  GtkWidget *espace_client;
  GtkWidget *ajouter_employee;
  GtkWidget *supprimer_employee;
  GtkWidget *confirmation_ajouter_employee;
  GtkWidget *confirmation_authentification_employee;
  GtkWidget *confirmation_authentification_client;
  GtkWidget *confirmation_supprimer_employee;
  GtkWidget *modifier_employee;
  GtkWidget *confirmation_modifier_employee;
  GtkWidget *ajouter_client_admin;
  GtkWidget *confirmation_ajouter_client_admin;
  GtkWidget *supprimer_client_admin;
  GtkWidget *confirmation_supprimer_client_admin;
  GtkWidget *modifier_client_admin;
  GtkWidget *confirmation_modifier_client_admin;
  GtkWidget *ajouter_client_employee;
  GtkWidget *confirmation_ajouter_client_employee;
  GtkWidget *modifier_client_employee;
  GtkWidget *confirmation_modifier_client_employee;
  GtkWidget *supprimer_client_employee;
  GtkWidget *confirmation_supprimer_client_employee;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  authentification_utilisateur = create_authentification_utilisateur ();
  gtk_widget_show (authentification_utilisateur);


  gtk_main ();
  return 0;
}

