/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window100 (void)
{
  GtkWidget *window100;
  GtkWidget *fixed100;
  GtkWidget *button103;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image100;
  GtkWidget *label101;
  GtkWidget *label100;
  GtkWidget *button100;

  window100 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window100), _("Gestion d'Hotel"));
  gtk_window_set_default_size (GTK_WINDOW (window100), 400, 300);

  fixed100 = gtk_fixed_new ();
  gtk_widget_show (fixed100);
  gtk_container_add (GTK_CONTAINER (window100), fixed100);

  button103 = gtk_button_new ();
  gtk_widget_show (button103);
  gtk_fixed_put (GTK_FIXED (fixed100), button103, 40, 256);
  gtk_widget_set_size_request (button103, 80, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button103), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image100 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image100);
  gtk_box_pack_start (GTK_BOX (hbox1), image100, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox1), label101, FALSE, FALSE, 0);

  label100 = gtk_label_new (_("Gestion d'Hotel"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed100), label100, 104, 16);
  gtk_widget_set_size_request (label100, 168, 56);

  button100 = gtk_button_new_with_mnemonic (_("Gestion d Hebergement "));
  gtk_widget_show (button100);
  gtk_fixed_put (GTK_FIXED (fixed100), button100, 80, 120);
  gtk_widget_set_size_request (button100, 232, 72);

  g_signal_connect ((gpointer) button100, "clicked",
                    G_CALLBACK (on_button100_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window100, window100, "window100");
  GLADE_HOOKUP_OBJECT (window100, fixed100, "fixed100");
  GLADE_HOOKUP_OBJECT (window100, button103, "button103");
  GLADE_HOOKUP_OBJECT (window100, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window100, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window100, image100, "image100");
  GLADE_HOOKUP_OBJECT (window100, label101, "label101");
  GLADE_HOOKUP_OBJECT (window100, label100, "label100");
  GLADE_HOOKUP_OBJECT (window100, button100, "button100");

  return window100;
}

GtkWidget*
create_window101 (void)
{
  GtkWidget *window101;
  GtkWidget *fixed101;
  GtkWidget *treeview100;
  GtkWidget *label102;
  GtkWidget *button107;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label700;
  GtkWidget *button104;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label400;
  GtkWidget *button105;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label500;
  GtkWidget *button106;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label600;
  GtkWidget *button120;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image101;
  GtkWidget *label703;

  window101 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window101), _("Gestion d'Hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window101), 800, 600);

  fixed101 = gtk_fixed_new ();
  gtk_widget_show (fixed101);
  gtk_container_add (GTK_CONTAINER (window101), fixed101);

  treeview100 = gtk_tree_view_new ();
  gtk_widget_show (treeview100);
  gtk_fixed_put (GTK_FIXED (fixed101), treeview100, 80, 72);
  gtk_widget_set_size_request (treeview100, 608, 312);

  label102 = gtk_label_new (_("Gestion d'Hebergement"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed101), label102, 264, 0);
  gtk_widget_set_size_request (label102, 200, 72);

  button107 = gtk_button_new ();
  gtk_widget_show (button107);
  gtk_fixed_put (GTK_FIXED (fixed101), button107, 56, 488);
  gtk_widget_set_size_request (button107, 96, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button107), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label700 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label700);
  gtk_box_pack_start (GTK_BOX (hbox5), label700, FALSE, FALSE, 0);

  button104 = gtk_button_new ();
  gtk_widget_show (button104);
  gtk_fixed_put (GTK_FIXED (fixed101), button104, 112, 432);
  gtk_widget_set_size_request (button104, 96, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button104), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label400 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label400);
  gtk_box_pack_start (GTK_BOX (hbox2), label400, FALSE, FALSE, 0);

  button105 = gtk_button_new ();
  gtk_widget_show (button105);
  gtk_fixed_put (GTK_FIXED (fixed101), button105, 240, 432);
  gtk_widget_set_size_request (button105, 96, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button105), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label500 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label500);
  gtk_box_pack_start (GTK_BOX (hbox3), label500, FALSE, FALSE, 0);

  button106 = gtk_button_new ();
  gtk_widget_show (button106);
  gtk_fixed_put (GTK_FIXED (fixed101), button106, 368, 432);
  gtk_widget_set_size_request (button106, 112, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button106), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label600 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label600);
  gtk_box_pack_start (GTK_BOX (hbox4), label600, FALSE, FALSE, 0);

  button120 = gtk_button_new ();
  gtk_widget_show (button120);
  gtk_fixed_put (GTK_FIXED (fixed101), button120, 520, 432);
  gtk_widget_set_size_request (button120, 192, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button120), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image101 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image101);
  gtk_box_pack_start (GTK_BOX (hbox18), image101, FALSE, FALSE, 0);

  label703 = gtk_label_new_with_mnemonic (_("Ajouter une reservation"));
  gtk_widget_show (label703);
  gtk_box_pack_start (GTK_BOX (hbox18), label703, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button107, "clicked",
                    G_CALLBACK (on_button107_clicked),
                    NULL);
  g_signal_connect ((gpointer) button104, "clicked",
                    G_CALLBACK (on_button104_clicked),
                    NULL);
  g_signal_connect ((gpointer) button105, "clicked",
                    G_CALLBACK (on_button105_clicked),
                    NULL);
  g_signal_connect ((gpointer) button106, "clicked",
                    G_CALLBACK (on_button106_clicked),
                    NULL);
  g_signal_connect ((gpointer) button120, "clicked",
                    G_CALLBACK (on_button120_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window101, window101, "window101");
  GLADE_HOOKUP_OBJECT (window101, fixed101, "fixed101");
  GLADE_HOOKUP_OBJECT (window101, treeview100, "treeview100");
  GLADE_HOOKUP_OBJECT (window101, label102, "label102");
  GLADE_HOOKUP_OBJECT (window101, button107, "button107");
  GLADE_HOOKUP_OBJECT (window101, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window101, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window101, image5, "image5");
  GLADE_HOOKUP_OBJECT (window101, label700, "label700");
  GLADE_HOOKUP_OBJECT (window101, button104, "button104");
  GLADE_HOOKUP_OBJECT (window101, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window101, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window101, image2, "image2");
  GLADE_HOOKUP_OBJECT (window101, label400, "label400");
  GLADE_HOOKUP_OBJECT (window101, button105, "button105");
  GLADE_HOOKUP_OBJECT (window101, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window101, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window101, image3, "image3");
  GLADE_HOOKUP_OBJECT (window101, label500, "label500");
  GLADE_HOOKUP_OBJECT (window101, button106, "button106");
  GLADE_HOOKUP_OBJECT (window101, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window101, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window101, image4, "image4");
  GLADE_HOOKUP_OBJECT (window101, label600, "label600");
  GLADE_HOOKUP_OBJECT (window101, button120, "button120");
  GLADE_HOOKUP_OBJECT (window101, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window101, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window101, image101, "image101");
  GLADE_HOOKUP_OBJECT (window101, label703, "label703");

  return window101;
}

GtkWidget*
create_window102 (void)
{
  GtkWidget *window102;
  GtkWidget *fixed102;
  GtkWidget *label107;
  GtkWidget *entry100;
  GtkWidget *entry101;
  GtkWidget *entry102;
  GtkWidget *label108;
  GtkWidget *label106;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *label105;
  GtkWidget *button108;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label14;
  GtkWidget *button109;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label15;
  GtkWidget *button110;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label17;

  window102 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window102), _("Modifier un Hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window102), 400, 600);

  fixed102 = gtk_fixed_new ();
  gtk_widget_show (fixed102);
  gtk_container_add (GTK_CONTAINER (window102), fixed102);

  label107 = gtk_label_new (_("Prix par nuite "));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed102), label107, 40, 224);
  gtk_widget_set_size_request (label107, 120, 40);

  entry100 = gtk_entry_new ();
  gtk_widget_show (entry100);
  gtk_fixed_put (GTK_FIXED (fixed102), entry100, 168, 176);
  gtk_widget_set_size_request (entry100, 152, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry100), 8226);

  entry101 = gtk_entry_new ();
  gtk_widget_show (entry101);
  gtk_fixed_put (GTK_FIXED (fixed102), entry101, 168, 232);
  gtk_widget_set_size_request (entry101, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry101), 8226);

  entry102 = gtk_entry_new ();
  gtk_widget_show (entry102);
  gtk_fixed_put (GTK_FIXED (fixed102), entry102, 168, 288);
  gtk_widget_set_size_request (entry102, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry102), 8226);

  label108 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed102), label108, 40, 280);
  gtk_widget_set_size_request (label108, 104, 40);

  label106 = gtk_label_new (_("Nom d'hotel"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed102), label106, 40, 168);
  gtk_widget_set_size_request (label106, 120, 48);

  label106 = gtk_label_new ("");
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed102), label106, 224, 480);
  gtk_widget_set_size_request (label106, 152, 56);

  label103 = gtk_label_new (_("Modifier un hebergement"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed102), label103, 112, 8);
  gtk_widget_set_size_request (label103, 184, 48);

  label104 = gtk_label_new (_("ID d'Hebergement"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed102), label104, 32, 64);
  gtk_widget_set_size_request (label104, 168, 56);

  label105 = gtk_label_new ("");
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed102), label105, 192, 64);
  gtk_widget_set_size_request (label105, 128, 56);

  button108 = gtk_button_new ();
  gtk_widget_show (button108);
  gtk_fixed_put (GTK_FIXED (fixed102), button108, 216, 400);
  gtk_widget_set_size_request (button108, 96, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button108), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox6), label14, FALSE, FALSE, 0);

  button109 = gtk_button_new ();
  gtk_widget_show (button109);
  gtk_fixed_put (GTK_FIXED (fixed102), button109, 96, 400);
  gtk_widget_set_size_request (button109, 88, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button109), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox7), label15, FALSE, FALSE, 0);

  button110 = gtk_button_new ();
  gtk_widget_show (button110);
  gtk_fixed_put (GTK_FIXED (fixed102), button110, 56, 496);
  gtk_widget_set_size_request (button110, 74, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button110), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button108, "clicked",
                    G_CALLBACK (on_button108_clicked),
                    NULL);
  g_signal_connect ((gpointer) button109, "clicked",
                    G_CALLBACK (on_button109_clicked),
                    NULL);
  g_signal_connect ((gpointer) button110, "clicked",
                    G_CALLBACK (on_button110_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window102, window102, "window102");
  GLADE_HOOKUP_OBJECT (window102, fixed102, "fixed102");
  GLADE_HOOKUP_OBJECT (window102, label107, "label107");
  GLADE_HOOKUP_OBJECT (window102, entry100, "entry100");
  GLADE_HOOKUP_OBJECT (window102, entry101, "entry101");
  GLADE_HOOKUP_OBJECT (window102, entry102, "entry102");
  GLADE_HOOKUP_OBJECT (window102, label108, "label108");
  GLADE_HOOKUP_OBJECT (window102, label106, "label106");
  GLADE_HOOKUP_OBJECT (window102, label106, "label106");
  GLADE_HOOKUP_OBJECT (window102, label103, "label103");
  GLADE_HOOKUP_OBJECT (window102, label104, "label104");
  GLADE_HOOKUP_OBJECT (window102, label105, "label105");
  GLADE_HOOKUP_OBJECT (window102, button108, "button108");
  GLADE_HOOKUP_OBJECT (window102, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window102, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window102, image6, "image6");
  GLADE_HOOKUP_OBJECT (window102, label14, "label14");
  GLADE_HOOKUP_OBJECT (window102, button109, "button109");
  GLADE_HOOKUP_OBJECT (window102, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window102, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window102, image7, "image7");
  GLADE_HOOKUP_OBJECT (window102, label15, "label15");
  GLADE_HOOKUP_OBJECT (window102, button110, "button110");
  GLADE_HOOKUP_OBJECT (window102, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window102, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window102, image8, "image8");
  GLADE_HOOKUP_OBJECT (window102, label17, "label17");

  return window102;
}

GtkWidget*
create_window103 (void)
{
  GtkWidget *window103;
  GtkWidget *fixed103;
  GtkWidget *label107;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label106;
  GtkWidget *label108;
  GtkWidget *label105;
  GtkWidget *label109;
  GtkWidget *button111;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label24;
  GtkWidget *label702;
  GtkWidget *button112;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label25;
  GtkWidget *button113;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label26;

  window103 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window103), _("Ajouter un Hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window103), 400, 600);

  fixed103 = gtk_fixed_new ();
  gtk_widget_show (fixed103);
  gtk_container_add (GTK_CONTAINER (window103), fixed103);

  label107 = gtk_label_new (_("Nom d'hotel"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed103), label107, 48, 200);
  gtk_widget_set_size_request (label107, 136, 48);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed103), entry4, 168, 152);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed103), entry5, 168, 208);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed103), entry6, 168, 272);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed103), entry7, 168, 328);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label106 = gtk_label_new (_("ID d'Hebergement"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed103), label106, 16, 144);
  gtk_widget_set_size_request (label106, 168, 48);

  label108 = gtk_label_new (_("Prix par nuite"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed103), label108, 32, 264);
  gtk_widget_set_size_request (label108, 152, 40);

  label105 = gtk_label_new (_("Ajouter un hebergement"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed103), label105, 128, 40);
  gtk_widget_set_size_request (label105, 176, 48);

  label109 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed103), label109, 48, 312);
  gtk_widget_set_size_request (label109, 144, 64);

  button111 = gtk_button_new ();
  gtk_widget_show (button111);
  gtk_fixed_put (GTK_FIXED (fixed103), button111, 216, 456);
  gtk_widget_set_size_request (button111, 96, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button111), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox10), label24, FALSE, FALSE, 0);

  label702 = gtk_label_new ("");
  gtk_widget_show (label702);
  gtk_fixed_put (GTK_FIXED (fixed103), label702, 200, 520);
  gtk_widget_set_size_request (label702, 192, 72);

  button112 = gtk_button_new ();
  gtk_widget_show (button112);
  gtk_fixed_put (GTK_FIXED (fixed103), button112, 72, 456);
  gtk_widget_set_size_request (button112, 104, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button112), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox11), label25, FALSE, FALSE, 0);

  button113 = gtk_button_new ();
  gtk_widget_show (button113);
  gtk_fixed_put (GTK_FIXED (fixed103), button113, 40, 528);
  gtk_widget_set_size_request (button113, 88, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button113), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox12), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button111, "clicked",
                    G_CALLBACK (on_button111_clicked),
                    NULL);
  g_signal_connect ((gpointer) button112, "clicked",
                    G_CALLBACK (on_button112_clicked),
                    NULL);
  g_signal_connect ((gpointer) button113, "clicked",
                    G_CALLBACK (on_button113_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window103, window103, "window103");
  GLADE_HOOKUP_OBJECT (window103, fixed103, "fixed103");
  GLADE_HOOKUP_OBJECT (window103, label107, "label107");
  GLADE_HOOKUP_OBJECT (window103, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window103, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window103, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window103, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window103, label106, "label106");
  GLADE_HOOKUP_OBJECT (window103, label108, "label108");
  GLADE_HOOKUP_OBJECT (window103, label105, "label105");
  GLADE_HOOKUP_OBJECT (window103, label109, "label109");
  GLADE_HOOKUP_OBJECT (window103, button111, "button111");
  GLADE_HOOKUP_OBJECT (window103, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window103, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window103, image10, "image10");
  GLADE_HOOKUP_OBJECT (window103, label24, "label24");
  GLADE_HOOKUP_OBJECT (window103, label702, "label702");
  GLADE_HOOKUP_OBJECT (window103, button112, "button112");
  GLADE_HOOKUP_OBJECT (window103, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window103, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window103, image11, "image11");
  GLADE_HOOKUP_OBJECT (window103, label25, "label25");
  GLADE_HOOKUP_OBJECT (window103, button113, "button113");
  GLADE_HOOKUP_OBJECT (window103, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window103, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window103, image12, "image12");
  GLADE_HOOKUP_OBJECT (window103, label26, "label26");

  return window103;
}

GtkWidget*
create_window104 (void)
{
  GtkWidget *window104;
  GtkWidget *fixed104;
  GtkWidget *label110;
  GtkWidget *button115;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label29;
  GtkWidget *combobox100;
  GtkWidget *button116;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label28;

  window104 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window104), _("Selectionner l'Hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window104), 400, 200);

  fixed104 = gtk_fixed_new ();
  gtk_widget_show (fixed104);
  gtk_container_add (GTK_CONTAINER (window104), fixed104);

  label110 = gtk_label_new (_("Selectionner l'hotel a modifier"));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed104), label110, 96, 24);
  gtk_widget_set_size_request (label110, 224, 56);

  button115 = gtk_button_new ();
  gtk_widget_show (button115);
  gtk_fixed_put (GTK_FIXED (fixed104), button115, 224, 216);
  gtk_widget_set_size_request (button115, 120, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button115), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Selectionner"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox14), label29, FALSE, FALSE, 0);

  combobox100 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox100);
  gtk_fixed_put (GTK_FIXED (fixed104), combobox100, 112, 120);
  gtk_widget_set_size_request (combobox100, 176, 32);

  button116 = gtk_button_new ();
  gtk_widget_show (button116);
  gtk_fixed_put (GTK_FIXED (fixed104), button116, 40, 248);
  gtk_widget_set_size_request (button116, 96, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button116), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox13), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button115, "clicked",
                    G_CALLBACK (on_button115_clicked),
                    NULL);
  g_signal_connect ((gpointer) button116, "clicked",
                    G_CALLBACK (on_button116_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window104, window104, "window104");
  GLADE_HOOKUP_OBJECT (window104, fixed104, "fixed104");
  GLADE_HOOKUP_OBJECT (window104, label110, "label110");
  GLADE_HOOKUP_OBJECT (window104, button115, "button115");
  GLADE_HOOKUP_OBJECT (window104, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window104, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window104, image14, "image14");
  GLADE_HOOKUP_OBJECT (window104, label29, "label29");
  GLADE_HOOKUP_OBJECT (window104, combobox100, "combobox100");
  GLADE_HOOKUP_OBJECT (window104, button116, "button116");
  GLADE_HOOKUP_OBJECT (window104, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window104, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window104, image13, "image13");
  GLADE_HOOKUP_OBJECT (window104, label28, "label28");

  return window104;
}

GtkWidget*
create_window105 (void)
{
  GtkWidget *window105;
  GtkWidget *fixed6;
  GtkWidget *label111;
  GtkWidget *button117;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label32;
  GtkWidget *label701;
  GtkWidget *combobox101;
  GtkWidget *button119;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label33;
  GtkWidget *button118;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label31;

  window105 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window105), _("Supprimer l'hebergement"));
  gtk_window_set_default_size (GTK_WINDOW (window105), 400, 200);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window105), fixed6);

  label111 = gtk_label_new (_("Selectionner l'hotel a supprimer"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed6), label111, 40, 16);
  gtk_widget_set_size_request (label111, 312, 64);

  button117 = gtk_button_new ();
  gtk_widget_show (button117);
  gtk_fixed_put (GTK_FIXED (fixed6), button117, 200, 192);
  gtk_widget_set_size_request (button117, 112, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button117), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox16), label32, FALSE, FALSE, 0);

  label701 = gtk_label_new ("");
  gtk_widget_show (label701);
  gtk_fixed_put (GTK_FIXED (fixed6), label701, 192, 240);
  gtk_widget_set_size_request (label701, 208, 48);

  combobox101 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox101);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox101, 112, 112);
  gtk_widget_set_size_request (combobox101, 176, 32);

  button119 = gtk_button_new ();
  gtk_widget_show (button119);
  gtk_fixed_put (GTK_FIXED (fixed6), button119, 32, 256);
  gtk_widget_set_size_request (button119, 88, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button119), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox17), label33, FALSE, FALSE, 0);

  button118 = gtk_button_new ();
  gtk_widget_show (button118);
  gtk_fixed_put (GTK_FIXED (fixed6), button118, 72, 192);
  gtk_widget_set_size_request (button118, 96, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button118), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox15), label31, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button117, "clicked",
                    G_CALLBACK (on_button117_clicked),
                    NULL);
  g_signal_connect ((gpointer) button119, "clicked",
                    G_CALLBACK (on_button119_clicked),
                    NULL);
  g_signal_connect ((gpointer) button118, "clicked",
                    G_CALLBACK (on_button118_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window105, window105, "window105");
  GLADE_HOOKUP_OBJECT (window105, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window105, label111, "label111");
  GLADE_HOOKUP_OBJECT (window105, button117, "button117");
  GLADE_HOOKUP_OBJECT (window105, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window105, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window105, image16, "image16");
  GLADE_HOOKUP_OBJECT (window105, label32, "label32");
  GLADE_HOOKUP_OBJECT (window105, label701, "label701");
  GLADE_HOOKUP_OBJECT (window105, combobox101, "combobox101");
  GLADE_HOOKUP_OBJECT (window105, button119, "button119");
  GLADE_HOOKUP_OBJECT (window105, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window105, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window105, image17, "image17");
  GLADE_HOOKUP_OBJECT (window105, label33, "label33");
  GLADE_HOOKUP_OBJECT (window105, button118, "button118");
  GLADE_HOOKUP_OBJECT (window105, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window105, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window105, image15, "image15");
  GLADE_HOOKUP_OBJECT (window105, label31, "label31");

  return window105;
}

GtkWidget*
create_window106 (void)
{
  GtkWidget *window106;
  GtkWidget *fixed105;
  GtkWidget *label704;
  GtkWidget *combobox102;
  GtkWidget *button121;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image103;
  GtkWidget *label707;
  GtkWidget *button122;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image102;
  GtkWidget *label706;

  window106 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window106), _("Selection de la destination"));
  gtk_window_set_default_size (GTK_WINDOW (window106), 400, 200);

  fixed105 = gtk_fixed_new ();
  gtk_widget_show (fixed105);
  gtk_container_add (GTK_CONTAINER (window106), fixed105);

  label704 = gtk_label_new (_("Selectionner la destination"));
  gtk_widget_show (label704);
  gtk_fixed_put (GTK_FIXED (fixed105), label704, 96, 40);
  gtk_widget_set_size_request (label704, 200, 40);

  combobox102 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox102);
  gtk_fixed_put (GTK_FIXED (fixed105), combobox102, 104, 120);
  gtk_widget_set_size_request (combobox102, 200, 32);

  button121 = gtk_button_new ();
  gtk_widget_show (button121);
  gtk_fixed_put (GTK_FIXED (fixed105), button121, 216, 224);
  gtk_widget_set_size_request (button121, 144, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button121), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image103 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image103);
  gtk_box_pack_start (GTK_BOX (hbox20), image103, FALSE, FALSE, 0);

  label707 = gtk_label_new_with_mnemonic (_("Selectionner"));
  gtk_widget_show (label707);
  gtk_box_pack_start (GTK_BOX (hbox20), label707, FALSE, FALSE, 0);

  button122 = gtk_button_new ();
  gtk_widget_show (button122);
  gtk_fixed_put (GTK_FIXED (fixed105), button122, 32, 224);
  gtk_widget_set_size_request (button122, 120, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button122), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image102 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image102);
  gtk_box_pack_start (GTK_BOX (hbox19), image102, FALSE, FALSE, 0);

  label706 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label706);
  gtk_box_pack_start (GTK_BOX (hbox19), label706, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button121, "clicked",
                    G_CALLBACK (on_button121_clicked),
                    NULL);
  g_signal_connect ((gpointer) button122, "clicked",
                    G_CALLBACK (on_button122_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window106, window106, "window106");
  GLADE_HOOKUP_OBJECT (window106, fixed105, "fixed105");
  GLADE_HOOKUP_OBJECT (window106, label704, "label704");
  GLADE_HOOKUP_OBJECT (window106, combobox102, "combobox102");
  GLADE_HOOKUP_OBJECT (window106, button121, "button121");
  GLADE_HOOKUP_OBJECT (window106, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window106, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window106, image103, "image103");
  GLADE_HOOKUP_OBJECT (window106, label707, "label707");
  GLADE_HOOKUP_OBJECT (window106, button122, "button122");
  GLADE_HOOKUP_OBJECT (window106, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window106, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window106, image102, "image102");
  GLADE_HOOKUP_OBJECT (window106, label706, "label706");

  return window106;
}

GtkWidget*
create_window107 (void)
{
  GtkWidget *window107;
  GtkWidget *fixed106;
  GtkWidget *label708;
  GtkWidget *combobox103;
  GtkWidget *button123;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image105;
  GtkWidget *label710;
  GtkWidget *button124;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image104;
  GtkWidget *label709;

  window107 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window107), _("Selection d'hotel"));
  gtk_window_set_default_size (GTK_WINDOW (window107), 400, 200);

  fixed106 = gtk_fixed_new ();
  gtk_widget_show (fixed106);
  gtk_container_add (GTK_CONTAINER (window107), fixed106);

  label708 = gtk_label_new (_("Selectionner l'hotel a reserver"));
  gtk_widget_show (label708);
  gtk_fixed_put (GTK_FIXED (fixed106), label708, 72, 16);
  gtk_widget_set_size_request (label708, 272, 64);

  combobox103 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox103);
  gtk_fixed_put (GTK_FIXED (fixed106), combobox103, 104, 104);
  gtk_widget_set_size_request (combobox103, 192, 32);

  button123 = gtk_button_new ();
  gtk_widget_show (button123);
  gtk_fixed_put (GTK_FIXED (fixed106), button123, 240, 192);
  gtk_widget_set_size_request (button123, 128, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button123), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image105 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image105);
  gtk_box_pack_start (GTK_BOX (hbox22), image105, FALSE, FALSE, 0);

  label710 = gtk_label_new_with_mnemonic (_("Selectionner"));
  gtk_widget_show (label710);
  gtk_box_pack_start (GTK_BOX (hbox22), label710, FALSE, FALSE, 0);

  button124 = gtk_button_new ();
  gtk_widget_show (button124);
  gtk_fixed_put (GTK_FIXED (fixed106), button124, 80, 192);
  gtk_widget_set_size_request (button124, 120, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button124), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image104 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image104);
  gtk_box_pack_start (GTK_BOX (hbox21), image104, FALSE, FALSE, 0);

  label709 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label709);
  gtk_box_pack_start (GTK_BOX (hbox21), label709, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button123, "clicked",
                    G_CALLBACK (on_button123_clicked),
                    NULL);
  g_signal_connect ((gpointer) button124, "clicked",
                    G_CALLBACK (on_button124_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window107, window107, "window107");
  GLADE_HOOKUP_OBJECT (window107, fixed106, "fixed106");
  GLADE_HOOKUP_OBJECT (window107, label708, "label708");
  GLADE_HOOKUP_OBJECT (window107, combobox103, "combobox103");
  GLADE_HOOKUP_OBJECT (window107, button123, "button123");
  GLADE_HOOKUP_OBJECT (window107, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window107, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window107, image105, "image105");
  GLADE_HOOKUP_OBJECT (window107, label710, "label710");
  GLADE_HOOKUP_OBJECT (window107, button124, "button124");
  GLADE_HOOKUP_OBJECT (window107, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window107, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window107, image104, "image104");
  GLADE_HOOKUP_OBJECT (window107, label709, "label709");

  return window107;
}

GtkWidget*
create_window108 (void)
{
  GtkWidget *window108;
  GtkWidget *fixed107;
  GtkWidget *label711;
  GtkWidget *label712;
  GtkWidget *label713;
  GtkWidget *label716;
  GtkWidget *label718;
  GtkWidget *label719;
  GtkWidget *label714;
  GtkWidget *label720;
  GtkWidget *entry103;
  GtkWidget *label721;
  GtkWidget *label722;
  GtkWidget *label723;
  GtkObject *spinbutton100_adj;
  GtkWidget *spinbutton100;
  GtkObject *spinbutton101_adj;
  GtkWidget *spinbutton101;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label724;
  GtkWidget *label725;
  GtkWidget *label726;
  GtkWidget *entry104;
  GtkWidget *label731;
  GtkWidget *label729;
  GtkWidget *label730;
  GtkWidget *label733;
  GtkWidget *entry105;
  GtkWidget *combobox105;
  GtkWidget *label717;
  GtkWidget *label715;
  GtkWidget *button125;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image106;
  GtkWidget *label727;
  GtkWidget *button126;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image107;
  GtkWidget *label732;
  GtkWidget *button127;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image108;
  GtkWidget *label734;
  GtkWidget *label735;
  GtkWidget *combobox104;
  GtkWidget *combobox106;
  GtkWidget *label728;

  window108 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window108), _("Ajout d'une reservation"));
  gtk_window_set_default_size (GTK_WINDOW (window108), 400, 900);

  fixed107 = gtk_fixed_new ();
  gtk_widget_show (fixed107);
  gtk_container_add (GTK_CONTAINER (window108), fixed107);

  label711 = gtk_label_new (_("Ajouter une reservation"));
  gtk_widget_show (label711);
  gtk_fixed_put (GTK_FIXED (fixed107), label711, 104, 8);
  gtk_widget_set_size_request (label711, 200, 56);

  label712 = gtk_label_new (_("ID hebergement :"));
  gtk_widget_show (label712);
  gtk_fixed_put (GTK_FIXED (fixed107), label712, 32, 56);
  gtk_widget_set_size_request (label712, 184, 40);

  label713 = gtk_label_new ("");
  gtk_widget_show (label713);
  gtk_fixed_put (GTK_FIXED (fixed107), label713, 152, 56);
  gtk_widget_set_size_request (label713, 152, 40);

  label716 = gtk_label_new (_("Nom d'Hotel :"));
  gtk_widget_show (label716);
  gtk_fixed_put (GTK_FIXED (fixed107), label716, 64, 96);
  gtk_widget_set_size_request (label716, 105, 33);

  label718 = gtk_label_new (_("Destination :"));
  gtk_widget_show (label718);
  gtk_fixed_put (GTK_FIXED (fixed107), label718, 48, 160);
  gtk_widget_set_size_request (label718, 136, 40);

  label719 = gtk_label_new ("");
  gtk_widget_show (label719);
  gtk_fixed_put (GTK_FIXED (fixed107), label719, 144, 160);
  gtk_widget_set_size_request (label719, 120, 40);

  label714 = gtk_label_new (_("Prix par nuite(en DT) :"));
  gtk_widget_show (label714);
  gtk_fixed_put (GTK_FIXED (fixed107), label714, 32, 120);
  gtk_widget_set_size_request (label714, 160, 48);

  label720 = gtk_label_new (_("ID Reservation "));
  gtk_widget_show (label720);
  gtk_fixed_put (GTK_FIXED (fixed107), label720, 16, 224);
  gtk_widget_set_size_request (label720, 152, 48);

  entry103 = gtk_entry_new ();
  gtk_widget_show (entry103);
  gtk_fixed_put (GTK_FIXED (fixed107), entry103, 152, 232);
  gtk_widget_set_size_request (entry103, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry103), 8226);

  label721 = gtk_label_new (_("Date de depart"));
  gtk_widget_show (label721);
  gtk_fixed_put (GTK_FIXED (fixed107), label721, 40, 304);
  gtk_widget_set_size_request (label721, 128, 32);

  label722 = gtk_label_new (_("Date d'arrivee"));
  gtk_widget_show (label722);
  gtk_fixed_put (GTK_FIXED (fixed107), label722, 208, 304);
  gtk_widget_set_size_request (label722, 144, 24);

  label723 = gtk_label_new (_("Pension :"));
  gtk_widget_show (label723);
  gtk_fixed_put (GTK_FIXED (fixed107), label723, 32, 392);
  gtk_widget_set_size_request (label723, 96, 32);

  spinbutton100_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton100 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton100_adj), 5, 0);
  gtk_widget_show (spinbutton100);
  gtk_fixed_put (GTK_FIXED (fixed107), spinbutton100, 48, 496);
  gtk_widget_set_size_request (spinbutton100, 60, 27);

  spinbutton101_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton101 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton101_adj), 5, 0);
  gtk_widget_show (spinbutton101);
  gtk_fixed_put (GTK_FIXED (fixed107), spinbutton101, 152, 496);
  gtk_widget_set_size_request (spinbutton101, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 5, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed107), spinbutton3, 248, 496);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label724 = gtk_label_new (_("Personne(s)"));
  gtk_widget_show (label724);
  gtk_fixed_put (GTK_FIXED (fixed107), label724, 8, 456);
  gtk_widget_set_size_request (label724, 128, 32);

  label725 = gtk_label_new (_("Chambre(s)"));
  gtk_widget_show (label725);
  gtk_fixed_put (GTK_FIXED (fixed107), label725, 120, 456);
  gtk_widget_set_size_request (label725, 120, 32);

  label726 = gtk_label_new (_("Enfant(s)"));
  gtk_widget_show (label726);
  gtk_fixed_put (GTK_FIXED (fixed107), label726, 224, 456);
  gtk_widget_set_size_request (label726, 112, 32);

  entry104 = gtk_entry_new ();
  gtk_widget_show (entry104);
  gtk_fixed_put (GTK_FIXED (fixed107), entry104, 128, 784);
  gtk_widget_set_size_request (entry104, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry104), 8226);

  label731 = gtk_label_new (_("ID Client"));
  gtk_widget_show (label731);
  gtk_fixed_put (GTK_FIXED (fixed107), label731, 8, 768);
  gtk_widget_set_size_request (label731, 128, 64);

  label729 = gtk_label_new ("");
  gtk_widget_show (label729);
  gtk_fixed_put (GTK_FIXED (fixed107), label729, 16, 704);
  gtk_widget_set_size_request (label729, 216, 56);

  label730 = gtk_label_new ("");
  gtk_widget_show (label730);
  gtk_fixed_put (GTK_FIXED (fixed107), label730, 264, 704);
  gtk_widget_set_size_request (label730, 136, 56);

  label733 = gtk_label_new (_("Nombre de nuit(s)"));
  gtk_widget_show (label733);
  gtk_fixed_put (GTK_FIXED (fixed107), label733, 8, 544);
  gtk_widget_set_size_request (label733, 160, 32);

  entry105 = gtk_entry_new ();
  gtk_widget_show (entry105);
  gtk_fixed_put (GTK_FIXED (fixed107), entry105, 168, 544);
  gtk_widget_set_size_request (entry105, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry105), 8226);

  combobox105 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox105);
  gtk_fixed_put (GTK_FIXED (fixed107), combobox105, 208, 336);
  gtk_widget_set_size_request (combobox105, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("01/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("02/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("03/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("04/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("05/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("06/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("07/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("08/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("09/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("10/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("11/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("12/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("13/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("14/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("15/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox105), _("16/01/2020"));

  label717 = gtk_label_new ("");
  gtk_widget_show (label717);
  gtk_fixed_put (GTK_FIXED (fixed107), label717, 152, 88);
  gtk_widget_set_size_request (label717, 136, 48);

  label715 = gtk_label_new ("");
  gtk_widget_show (label715);
  gtk_fixed_put (GTK_FIXED (fixed107), label715, 152, 120);
  gtk_widget_set_size_request (label715, 144, 41);

  button125 = gtk_button_new ();
  gtk_widget_show (button125);
  gtk_fixed_put (GTK_FIXED (fixed107), button125, 144, 640);
  gtk_widget_set_size_request (button125, 128, 48);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button125), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image106 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image106);
  gtk_box_pack_start (GTK_BOX (hbox23), image106, FALSE, FALSE, 0);

  label727 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label727);
  gtk_box_pack_start (GTK_BOX (hbox23), label727, FALSE, FALSE, 0);

  button126 = gtk_button_new ();
  gtk_widget_show (button126);
  gtk_fixed_put (GTK_FIXED (fixed107), button126, 256, 824);
  gtk_widget_set_size_request (button126, 186, 32);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button126), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image107 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image107);
  gtk_box_pack_start (GTK_BOX (hbox24), image107, FALSE, FALSE, 0);

  label732 = gtk_label_new_with_mnemonic (_("Ajouter la reservation"));
  gtk_widget_show (label732);
  gtk_box_pack_start (GTK_BOX (hbox24), label732, FALSE, FALSE, 0);

  button127 = gtk_button_new ();
  gtk_widget_show (button127);
  gtk_fixed_put (GTK_FIXED (fixed107), button127, 32, 840);
  gtk_widget_set_size_request (button127, 82, 29);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button127), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image108 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image108);
  gtk_box_pack_start (GTK_BOX (hbox25), image108, FALSE, FALSE, 0);

  label734 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label734);
  gtk_box_pack_start (GTK_BOX (hbox25), label734, FALSE, FALSE, 0);

  label735 = gtk_label_new ("");
  gtk_widget_show (label735);
  gtk_fixed_put (GTK_FIXED (fixed107), label735, 128, 856);
  gtk_widget_set_size_request (label735, 168, 40);

  combobox104 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox104);
  gtk_fixed_put (GTK_FIXED (fixed107), combobox104, 24, 336);
  gtk_widget_set_size_request (combobox104, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("01/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("02/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("03/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("04/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("05/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("06/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("07/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("08/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("09/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("10/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("11/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("12/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("13/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("14/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("15/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox104), _("16/01/2020"));

  combobox106 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox106);
  gtk_fixed_put (GTK_FIXED (fixed107), combobox106, 128, 392);
  gtk_widget_set_size_request (combobox106, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox106), _("Complete"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox106), _("Demi-Prension"));

  label728 = gtk_label_new (_("Cliquer sur le button Valider pour afficher le montant totale"));
  gtk_widget_show (label728);
  gtk_fixed_put (GTK_FIXED (fixed107), label728, 8, 584);
  gtk_widget_set_size_request (label728, 432, 48);

  g_signal_connect ((gpointer) button125, "clicked",
                    G_CALLBACK (on_button125_clicked),
                    NULL);
  g_signal_connect ((gpointer) button126, "clicked",
                    G_CALLBACK (on_button126_clicked),
                    NULL);
  g_signal_connect ((gpointer) button127, "clicked",
                    G_CALLBACK (on_button127_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window108, window108, "window108");
  GLADE_HOOKUP_OBJECT (window108, fixed107, "fixed107");
  GLADE_HOOKUP_OBJECT (window108, label711, "label711");
  GLADE_HOOKUP_OBJECT (window108, label712, "label712");
  GLADE_HOOKUP_OBJECT (window108, label713, "label713");
  GLADE_HOOKUP_OBJECT (window108, label716, "label716");
  GLADE_HOOKUP_OBJECT (window108, label718, "label718");
  GLADE_HOOKUP_OBJECT (window108, label719, "label719");
  GLADE_HOOKUP_OBJECT (window108, label714, "label714");
  GLADE_HOOKUP_OBJECT (window108, label720, "label720");
  GLADE_HOOKUP_OBJECT (window108, entry103, "entry103");
  GLADE_HOOKUP_OBJECT (window108, label721, "label721");
  GLADE_HOOKUP_OBJECT (window108, label722, "label722");
  GLADE_HOOKUP_OBJECT (window108, label723, "label723");
  GLADE_HOOKUP_OBJECT (window108, spinbutton100, "spinbutton100");
  GLADE_HOOKUP_OBJECT (window108, spinbutton101, "spinbutton101");
  GLADE_HOOKUP_OBJECT (window108, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window108, label724, "label724");
  GLADE_HOOKUP_OBJECT (window108, label725, "label725");
  GLADE_HOOKUP_OBJECT (window108, label726, "label726");
  GLADE_HOOKUP_OBJECT (window108, entry104, "entry104");
  GLADE_HOOKUP_OBJECT (window108, label731, "label731");
  GLADE_HOOKUP_OBJECT (window108, label729, "label729");
  GLADE_HOOKUP_OBJECT (window108, label730, "label730");
  GLADE_HOOKUP_OBJECT (window108, label733, "label733");
  GLADE_HOOKUP_OBJECT (window108, entry105, "entry105");
  GLADE_HOOKUP_OBJECT (window108, combobox105, "combobox105");
  GLADE_HOOKUP_OBJECT (window108, label717, "label717");
  GLADE_HOOKUP_OBJECT (window108, label715, "label715");
  GLADE_HOOKUP_OBJECT (window108, button125, "button125");
  GLADE_HOOKUP_OBJECT (window108, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window108, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window108, image106, "image106");
  GLADE_HOOKUP_OBJECT (window108, label727, "label727");
  GLADE_HOOKUP_OBJECT (window108, button126, "button126");
  GLADE_HOOKUP_OBJECT (window108, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window108, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window108, image107, "image107");
  GLADE_HOOKUP_OBJECT (window108, label732, "label732");
  GLADE_HOOKUP_OBJECT (window108, button127, "button127");
  GLADE_HOOKUP_OBJECT (window108, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window108, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window108, image108, "image108");
  GLADE_HOOKUP_OBJECT (window108, label734, "label734");
  GLADE_HOOKUP_OBJECT (window108, label735, "label735");
  GLADE_HOOKUP_OBJECT (window108, combobox104, "combobox104");
  GLADE_HOOKUP_OBJECT (window108, combobox106, "combobox106");
  GLADE_HOOKUP_OBJECT (window108, label728, "label728");

  return window108;
}

GtkWidget*
create_window109 (void)
{
  GtkWidget *window109;
  GtkWidget *notebook1;
  GtkWidget *fixed108;
  GtkWidget *profile_admin;
  GtkWidget *fixed109;
  GtkWidget *image109;
  GtkWidget *label742;
  GtkWidget *label744;
  GtkWidget *button128;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image110;
  GtkWidget *label747;
  GtkWidget *label745;
  GtkWidget *image111;
  GtkWidget *button129;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image112;
  GtkWidget *label748;
  GtkWidget *label746;
  GtkWidget *label750;
  GtkWidget *label751;
  GtkWidget *label743;
  GtkWidget *label749;
  GtkWidget *button130;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image113;
  GtkWidget *label752;
  GtkWidget *label737;
  GtkWidget *fixed110;
  GtkWidget *label738;
  GtkWidget *fixed111;
  GtkWidget *label739;
  GtkWidget *fixed112;
  GtkWidget *label740;
  GtkWidget *fixed113;
  GtkWidget *label741;

  window109 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window109), _("Espace Client"));
  gtk_window_set_default_size (GTK_WINDOW (window109), 800, 800);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window109), notebook1);

  fixed108 = gtk_fixed_new ();
  gtk_widget_show (fixed108);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed108);

  profile_admin = gtk_label_new (_("Mon Profile"));
  gtk_widget_show (profile_admin);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), profile_admin);

  fixed109 = gtk_fixed_new ();
  gtk_widget_show (fixed109);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed109);

  image109 = create_pixmap (window109, "hotel1.jpeg");
  gtk_widget_show (image109);
  gtk_fixed_put (GTK_FIXED (fixed109), image109, 0, 88);
  gtk_widget_set_size_request (image109, 393, 224);

  label742 = gtk_label_new (_("Hotels disponible a "));
  gtk_widget_show (label742);
  gtk_fixed_put (GTK_FIXED (fixed109), label742, 32, 8);
  gtk_widget_set_size_request (label742, 256, 88);

  label744 = gtk_label_new (_("Prix par nuite en DT"));
  gtk_widget_show (label744);
  gtk_fixed_put (GTK_FIXED (fixed109), label744, 352, 144);
  gtk_widget_set_size_request (label744, 144, 40);

  button128 = gtk_button_new ();
  gtk_widget_show (button128);
  gtk_fixed_put (GTK_FIXED (fixed109), button128, 400, 224);
  gtk_widget_set_size_request (button128, 114, 45);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button128), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image110 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image110);
  gtk_box_pack_start (GTK_BOX (hbox26), image110, FALSE, FALSE, 0);

  label747 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label747);
  gtk_box_pack_start (GTK_BOX (hbox26), label747, FALSE, FALSE, 0);

  label745 = gtk_label_new (_("98"));
  gtk_widget_show (label745);
  gtk_fixed_put (GTK_FIXED (fixed109), label745, 496, 144);
  gtk_widget_set_size_request (label745, 64, 32);

  image111 = create_pixmap (window109, "hotel2.jpg");
  gtk_widget_show (image111);
  gtk_fixed_put (GTK_FIXED (fixed109), image111, 48, 392);
  gtk_widget_set_size_request (image111, 304, 184);

  button129 = gtk_button_new ();
  gtk_widget_show (button129);
  gtk_fixed_put (GTK_FIXED (fixed109), button129, 416, 496);
  gtk_widget_set_size_request (button129, 136, 48);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button129), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image112 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image112);
  gtk_box_pack_start (GTK_BOX (hbox27), image112, FALSE, FALSE, 0);

  label748 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label748);
  gtk_box_pack_start (GTK_BOX (hbox27), label748, FALSE, FALSE, 0);

  label746 = gtk_label_new (_("Tunis"));
  gtk_widget_show (label746);
  gtk_fixed_put (GTK_FIXED (fixed109), label746, 272, 32);
  gtk_widget_set_size_request (label746, 152, 40);

  label750 = gtk_label_new (_("Prix par nuite en DT"));
  gtk_widget_show (label750);
  gtk_fixed_put (GTK_FIXED (fixed109), label750, 352, 424);
  gtk_widget_set_size_request (label750, 192, 49);

  label751 = gtk_label_new (_("78"));
  gtk_widget_show (label751);
  gtk_fixed_put (GTK_FIXED (fixed109), label751, 528, 440);
  gtk_widget_set_size_request (label751, 57, 17);

  label743 = gtk_label_new (_("Sheraton"));
  gtk_widget_show (label743);
  gtk_fixed_put (GTK_FIXED (fixed109), label743, 384, 96);
  gtk_widget_set_size_request (label743, 112, 48);

  label749 = gtk_label_new (_("MouradiHotel"));
  gtk_widget_show (label749);
  gtk_fixed_put (GTK_FIXED (fixed109), label749, 392, 368);
  gtk_widget_set_size_request (label749, 160, 56);

  button130 = gtk_button_new ();
  gtk_widget_show (button130);
  gtk_fixed_put (GTK_FIXED (fixed109), button130, 672, 40);
  gtk_widget_set_size_request (button130, 136, 56);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button130), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image113 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image113);
  gtk_box_pack_start (GTK_BOX (hbox28), image113, FALSE, FALSE, 0);

  label752 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label752);
  gtk_box_pack_start (GTK_BOX (hbox28), label752, FALSE, FALSE, 0);

  label737 = gtk_label_new (_("Espace des hebergement"));
  gtk_widget_show (label737);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label737);

  fixed110 = gtk_fixed_new ();
  gtk_widget_show (fixed110);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed110);

  label738 = gtk_label_new (_("Espace des vols"));
  gtk_widget_show (label738);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label738);

  fixed111 = gtk_fixed_new ();
  gtk_widget_show (fixed111);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed111);

  label739 = gtk_label_new (_("Espace des excursions"));
  gtk_widget_show (label739);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label739);

  fixed112 = gtk_fixed_new ();
  gtk_widget_show (fixed112);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed112);

  label740 = gtk_label_new (_("Espace des factures"));
  gtk_widget_show (label740);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label740);

  fixed113 = gtk_fixed_new ();
  gtk_widget_show (fixed113);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed113);

  label741 = gtk_label_new (_("Espace des reclamations"));
  gtk_widget_show (label741);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label741);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window109, window109, "window109");
  GLADE_HOOKUP_OBJECT (window109, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window109, fixed108, "fixed108");
  GLADE_HOOKUP_OBJECT (window109, profile_admin, "profile_admin");
  GLADE_HOOKUP_OBJECT (window109, fixed109, "fixed109");
  GLADE_HOOKUP_OBJECT (window109, image109, "image109");
  GLADE_HOOKUP_OBJECT (window109, label742, "label742");
  GLADE_HOOKUP_OBJECT (window109, label744, "label744");
  GLADE_HOOKUP_OBJECT (window109, button128, "button128");
  GLADE_HOOKUP_OBJECT (window109, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window109, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window109, image110, "image110");
  GLADE_HOOKUP_OBJECT (window109, label747, "label747");
  GLADE_HOOKUP_OBJECT (window109, label745, "label745");
  GLADE_HOOKUP_OBJECT (window109, image111, "image111");
  GLADE_HOOKUP_OBJECT (window109, button129, "button129");
  GLADE_HOOKUP_OBJECT (window109, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window109, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window109, image112, "image112");
  GLADE_HOOKUP_OBJECT (window109, label748, "label748");
  GLADE_HOOKUP_OBJECT (window109, label746, "label746");
  GLADE_HOOKUP_OBJECT (window109, label750, "label750");
  GLADE_HOOKUP_OBJECT (window109, label751, "label751");
  GLADE_HOOKUP_OBJECT (window109, label743, "label743");
  GLADE_HOOKUP_OBJECT (window109, label749, "label749");
  GLADE_HOOKUP_OBJECT (window109, button130, "button130");
  GLADE_HOOKUP_OBJECT (window109, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window109, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window109, image113, "image113");
  GLADE_HOOKUP_OBJECT (window109, label752, "label752");
  GLADE_HOOKUP_OBJECT (window109, label737, "label737");
  GLADE_HOOKUP_OBJECT (window109, fixed110, "fixed110");
  GLADE_HOOKUP_OBJECT (window109, label738, "label738");
  GLADE_HOOKUP_OBJECT (window109, fixed111, "fixed111");
  GLADE_HOOKUP_OBJECT (window109, label739, "label739");
  GLADE_HOOKUP_OBJECT (window109, fixed112, "fixed112");
  GLADE_HOOKUP_OBJECT (window109, label740, "label740");
  GLADE_HOOKUP_OBJECT (window109, fixed113, "fixed113");
  GLADE_HOOKUP_OBJECT (window109, label741, "label741");

  return window109;
}

GtkWidget*
create_window110 (void)
{
  GtkWidget *window110;
  GtkWidget *fixed114;
  GtkWidget *label754;
  GtkWidget *label755;
  GtkWidget *label757;
  GtkWidget *label756;
  GtkWidget *label758;
  GtkWidget *label760;
  GtkWidget *label761;
  GtkWidget *label762;
  GtkWidget *entry106;
  GtkWidget *label763;
  GtkWidget *button131;
  GtkWidget *label764;
  GtkWidget *combobox107;
  GtkWidget *combobox108;
  GtkWidget *label765;
  GtkObject *spinbutton102_adj;
  GtkWidget *spinbutton102;
  GtkObject *spinbutton103_adj;
  GtkWidget *spinbutton103;
  GtkObject *spinbutton104_adj;
  GtkWidget *spinbutton104;
  GtkWidget *entry107;
  GtkWidget *combobox109;
  GtkWidget *label766;
  GtkWidget *label767;
  GtkWidget *label768;
  GtkWidget *label769;
  GtkWidget *label770;
  GtkWidget *label771;
  GtkWidget *button132;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image114;
  GtkWidget *label772;
  GtkWidget *label753;
  GtkWidget *label775;
  GtkWidget *label773;
  GtkWidget *label774;
  GtkWidget *button133;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image115;
  GtkWidget *label776;

  window110 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window110), _("Reserver"));
  gtk_window_set_default_size (GTK_WINDOW (window110), 400, 900);

  fixed114 = gtk_fixed_new ();
  gtk_widget_show (fixed114);
  gtk_container_add (GTK_CONTAINER (window110), fixed114);

  label754 = gtk_label_new (_("ID hebergement"));
  gtk_widget_show (label754);
  gtk_fixed_put (GTK_FIXED (fixed114), label754, 40, 72);
  gtk_widget_set_size_request (label754, 152, 72);

  label755 = gtk_label_new (_("D98"));
  gtk_widget_show (label755);
  gtk_fixed_put (GTK_FIXED (fixed114), label755, 160, 88);
  gtk_widget_set_size_request (label755, 88, 40);

  label757 = gtk_label_new (_("Sheraton"));
  gtk_widget_show (label757);
  gtk_fixed_put (GTK_FIXED (fixed114), label757, 160, 136);
  gtk_widget_set_size_request (label757, 89, 40);

  label756 = gtk_label_new (_("Nom d'hotel :"));
  gtk_widget_show (label756);
  gtk_fixed_put (GTK_FIXED (fixed114), label756, 48, 128);
  gtk_widget_set_size_request (label756, 128, 56);

  label758 = gtk_label_new (_("Prix par nuitee en DT :"));
  gtk_widget_show (label758);
  gtk_fixed_put (GTK_FIXED (fixed114), label758, 16, 176);
  gtk_widget_set_size_request (label758, 160, 56);

  label760 = gtk_label_new (_("98"));
  gtk_widget_show (label760);
  gtk_fixed_put (GTK_FIXED (fixed114), label760, 192, 192);
  gtk_widget_set_size_request (label760, 57, 17);

  label761 = gtk_label_new (_("Destination"));
  gtk_widget_show (label761);
  gtk_fixed_put (GTK_FIXED (fixed114), label761, 40, 232);
  gtk_widget_set_size_request (label761, 113, 48);

  label762 = gtk_label_new (_("Tunis"));
  gtk_widget_show (label762);
  gtk_fixed_put (GTK_FIXED (fixed114), label762, 160, 240);
  gtk_widget_set_size_request (label762, 104, 32);

  entry106 = gtk_entry_new ();
  gtk_widget_show (entry106);
  gtk_fixed_put (GTK_FIXED (fixed114), entry106, 152, 288);
  gtk_widget_set_size_request (entry106, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry106), 8226);

  label763 = gtk_label_new (_("ID reservation"));
  gtk_widget_show (label763);
  gtk_fixed_put (GTK_FIXED (fixed114), label763, 16, 280);
  gtk_widget_set_size_request (label763, 136, 48);

  button131 = gtk_button_new_with_mnemonic (_("Generer"));
  gtk_widget_show (button131);
  gtk_fixed_put (GTK_FIXED (fixed114), button131, 328, 288);
  gtk_widget_set_size_request (button131, 82, 29);

  label764 = gtk_label_new (_("Date de depart"));
  gtk_widget_show (label764);
  gtk_fixed_put (GTK_FIXED (fixed114), label764, 72, 344);
  gtk_widget_set_size_request (label764, 121, 17);

  combobox107 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox107);
  gtk_fixed_put (GTK_FIXED (fixed114), combobox107, 56, 376);
  gtk_widget_set_size_request (combobox107, 144, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("01/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("02/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("03/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("04/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("05/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("06/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("07/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("08/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("09/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("10/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("11/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("12/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("13/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("14/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("15/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox107), _("16/01/2020"));

  combobox108 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox108);
  gtk_fixed_put (GTK_FIXED (fixed114), combobox108, 232, 376);
  gtk_widget_set_size_request (combobox108, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("01/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("02/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("03/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("04/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("05/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("06/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("07/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("08/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("09/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("10/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("11/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("12/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("13/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("14/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("15/01/2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox108), _("16/01/2020"));

  label765 = gtk_label_new (_("Date d'arrive"));
  gtk_widget_show (label765);
  gtk_fixed_put (GTK_FIXED (fixed114), label765, 224, 344);
  gtk_widget_set_size_request (label765, 136, 24);

  spinbutton102_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton102 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton102_adj), 1, 0);
  gtk_widget_show (spinbutton102);
  gtk_fixed_put (GTK_FIXED (fixed114), spinbutton102, 56, 512);
  gtk_widget_set_size_request (spinbutton102, 60, 27);

  spinbutton103_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton103 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton103_adj), 1, 0);
  gtk_widget_show (spinbutton103);
  gtk_fixed_put (GTK_FIXED (fixed114), spinbutton103, 168, 512);
  gtk_widget_set_size_request (spinbutton103, 60, 27);

  spinbutton104_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton104 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton104_adj), 1, 0);
  gtk_widget_show (spinbutton104);
  gtk_fixed_put (GTK_FIXED (fixed114), spinbutton104, 280, 512);
  gtk_widget_set_size_request (spinbutton104, 60, 27);

  entry107 = gtk_entry_new ();
  gtk_widget_show (entry107);
  gtk_fixed_put (GTK_FIXED (fixed114), entry107, 168, 568);
  gtk_widget_set_size_request (entry107, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry107), 8226);

  combobox109 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox109);
  gtk_fixed_put (GTK_FIXED (fixed114), combobox109, 144, 424);
  gtk_widget_set_size_request (combobox109, 184, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox109), _("Complete"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox109), _("Demi_Pension"));

  label766 = gtk_label_new (_("Pension"));
  gtk_widget_show (label766);
  gtk_fixed_put (GTK_FIXED (fixed114), label766, 16, 416);
  gtk_widget_set_size_request (label766, 120, 48);

  label767 = gtk_label_new (_("Personnes"));
  gtk_widget_show (label767);
  gtk_fixed_put (GTK_FIXED (fixed114), label767, 24, 472);
  gtk_widget_set_size_request (label767, 112, 32);

  label768 = gtk_label_new (_("Chambres"));
  gtk_widget_show (label768);
  gtk_fixed_put (GTK_FIXED (fixed114), label768, 152, 472);
  gtk_widget_set_size_request (label768, 88, 32);

  label769 = gtk_label_new (_("Enfants"));
  gtk_widget_show (label769);
  gtk_fixed_put (GTK_FIXED (fixed114), label769, 264, 472);
  gtk_widget_set_size_request (label769, 96, 32);

  label770 = gtk_label_new (_("Nombre de nuits"));
  gtk_widget_show (label770);
  gtk_fixed_put (GTK_FIXED (fixed114), label770, 0, 560);
  gtk_widget_set_size_request (label770, 176, 56);

  label771 = gtk_label_new (_("Cliquer sur le button Valider pour afficher le montant totale"));
  gtk_widget_show (label771);
  gtk_fixed_put (GTK_FIXED (fixed114), label771, 0, 608);
  gtk_widget_set_size_request (label771, 424, 40);

  button132 = gtk_button_new ();
  gtk_widget_show (button132);
  gtk_fixed_put (GTK_FIXED (fixed114), button132, 144, 648);
  gtk_widget_set_size_request (button132, 136, 48);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button132), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image114 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image114);
  gtk_box_pack_start (GTK_BOX (hbox29), image114, FALSE, FALSE, 0);

  label772 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label772);
  gtk_box_pack_start (GTK_BOX (hbox29), label772, FALSE, FALSE, 0);

  label753 = gtk_label_new (_("Reserver votre hotel"));
  gtk_widget_show (label753);
  gtk_fixed_put (GTK_FIXED (fixed114), label753, 144, 24);
  gtk_widget_set_size_request (label753, 176, 80);

  label775 = gtk_label_new (_("ID client:"));
  gtk_widget_show (label775);
  gtk_fixed_put (GTK_FIXED (fixed114), label775, 16, 8);
  gtk_widget_set_size_request (label775, 112, 40);

  label773 = gtk_label_new ("");
  gtk_widget_show (label773);
  gtk_fixed_put (GTK_FIXED (fixed114), label773, 24, 712);
  gtk_widget_set_size_request (label773, 192, 40);

  label774 = gtk_label_new ("");
  gtk_widget_show (label774);
  gtk_fixed_put (GTK_FIXED (fixed114), label774, 264, 712);
  gtk_widget_set_size_request (label774, 144, 40);

  button133 = gtk_button_new ();
  gtk_widget_show (button133);
  gtk_fixed_put (GTK_FIXED (fixed114), button133, 224, 768);
  gtk_widget_set_size_request (button133, 218, 45);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button133), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image115 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image115);
  gtk_box_pack_start (GTK_BOX (hbox30), image115, FALSE, FALSE, 0);

  label776 = gtk_label_new_with_mnemonic (_("Confirmer la reservation"));
  gtk_widget_show (label776);
  gtk_box_pack_start (GTK_BOX (hbox30), label776, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window110, window110, "window110");
  GLADE_HOOKUP_OBJECT (window110, fixed114, "fixed114");
  GLADE_HOOKUP_OBJECT (window110, label754, "label754");
  GLADE_HOOKUP_OBJECT (window110, label755, "label755");
  GLADE_HOOKUP_OBJECT (window110, label757, "label757");
  GLADE_HOOKUP_OBJECT (window110, label756, "label756");
  GLADE_HOOKUP_OBJECT (window110, label758, "label758");
  GLADE_HOOKUP_OBJECT (window110, label760, "label760");
  GLADE_HOOKUP_OBJECT (window110, label761, "label761");
  GLADE_HOOKUP_OBJECT (window110, label762, "label762");
  GLADE_HOOKUP_OBJECT (window110, entry106, "entry106");
  GLADE_HOOKUP_OBJECT (window110, label763, "label763");
  GLADE_HOOKUP_OBJECT (window110, button131, "button131");
  GLADE_HOOKUP_OBJECT (window110, label764, "label764");
  GLADE_HOOKUP_OBJECT (window110, combobox107, "combobox107");
  GLADE_HOOKUP_OBJECT (window110, combobox108, "combobox108");
  GLADE_HOOKUP_OBJECT (window110, label765, "label765");
  GLADE_HOOKUP_OBJECT (window110, spinbutton102, "spinbutton102");
  GLADE_HOOKUP_OBJECT (window110, spinbutton103, "spinbutton103");
  GLADE_HOOKUP_OBJECT (window110, spinbutton104, "spinbutton104");
  GLADE_HOOKUP_OBJECT (window110, entry107, "entry107");
  GLADE_HOOKUP_OBJECT (window110, combobox109, "combobox109");
  GLADE_HOOKUP_OBJECT (window110, label766, "label766");
  GLADE_HOOKUP_OBJECT (window110, label767, "label767");
  GLADE_HOOKUP_OBJECT (window110, label768, "label768");
  GLADE_HOOKUP_OBJECT (window110, label769, "label769");
  GLADE_HOOKUP_OBJECT (window110, label770, "label770");
  GLADE_HOOKUP_OBJECT (window110, label771, "label771");
  GLADE_HOOKUP_OBJECT (window110, button132, "button132");
  GLADE_HOOKUP_OBJECT (window110, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window110, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window110, image114, "image114");
  GLADE_HOOKUP_OBJECT (window110, label772, "label772");
  GLADE_HOOKUP_OBJECT (window110, label753, "label753");
  GLADE_HOOKUP_OBJECT (window110, label775, "label775");
  GLADE_HOOKUP_OBJECT (window110, label773, "label773");
  GLADE_HOOKUP_OBJECT (window110, label774, "label774");
  GLADE_HOOKUP_OBJECT (window110, button133, "button133");
  GLADE_HOOKUP_OBJECT (window110, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window110, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window110, image115, "image115");
  GLADE_HOOKUP_OBJECT (window110, label776, "label776");

  return window110;
}

