/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window100 (void);
GtkWidget* create_window101 (void);
GtkWidget* create_window102 (void);
GtkWidget* create_window103 (void);
GtkWidget* create_window104 (void);
GtkWidget* create_window105 (void);
GtkWidget* create_window106 (void);
GtkWidget* create_window107 (void);
GtkWidget* create_window108 (void);
GtkWidget* create_espace_client (void);
GtkWidget* create_window110 (void);
GtkWidget* create_window111 (void);
GtkWidget* create_window112 (void);
GtkWidget* create_espace_employee (void);
GtkWidget* create_authentification_utilisateur (void);
GtkWidget* create_confirmation_authentification_admin (void);
GtkWidget* create_espace_admin (void);
GtkWidget* create_ajouter_employee (void);
GtkWidget* create_supprimer_employee (void);
GtkWidget* create_confirmation_ajouter_employee (void);
GtkWidget* create_confirmation_authentification_employee (void);
GtkWidget* create_confirmation_authentification_client (void);
GtkWidget* create_confirmation_supprimer_employee (void);
GtkWidget* create_modifier_employee (void);
GtkWidget* create_confirmation_modifier_employee (void);
GtkWidget* create_ajouter_client_admin (void);
GtkWidget* create_confirmation_ajouter_client_admin (void);
GtkWidget* create_supprimer_client_admin (void);
GtkWidget* create_confirmation_supprimer_client_admin (void);
GtkWidget* create_modifier_client_admin (void);
GtkWidget* create_confirmation_modifier_client_admin (void);
GtkWidget* create_ajouter_client_employee (void);
GtkWidget* create_confirmation_ajouter_client_employee (void);
GtkWidget* create_modifier_client_employee (void);
GtkWidget* create_confirmation_modifier_client_employee (void);
GtkWidget* create_supprimer_client_employee (void);
GtkWidget* create_confirmation_supprimer_client_employee (void);
GtkWidget* create_choisir_identifiant_modifier_employee (void);
GtkWidget* create_choisir_identifiant_modifier_client_employee (void);
GtkWidget* create_choisir_identifiant_modifier_client_admin (void);
